Repository openshift/windows-machine-config-operator, pull requests merged in 2020-04, with the labels that each got.

#17 Make operator deployable via OLM
  README.md
  deploy/olm-catalog/catalogsource.yaml
  deploy/olm-catalog/operatorgroup.yaml
  deploy/olm-catalog/subscription.yaml
  deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml
  deploy/olm-catalog/windows-machine-config-operator/0.0.0/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
Labels: approved, lgtm, size/L

#31 [docs] Fix link for SshKeyPair in README
  README.md
Labels: approved, lgtm

#30 [ci] Refactor tests to have global and local contexts
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/main_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#34 Bug 1817186: [wmco] Fix log panic and correct formatting of log messages
  cmd/manager/main.go
  pkg/controller/windowsmachineconfig/tracker/tracker.go
  pkg/controller/windowsmachineconfig/windows/windows.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
Labels: approved, bugzilla/valid-bug, lgtm

#32 [wmco] Ensure files required by WMCO are present
  cmd/manager/main.go
  cmd/manager/main_test.go
  hack/unit.sh
  pkg/controller/wellknownlocations/wellknownlocations.go
Labels: approved, lgtm

#21 [wmco] Hybrid overlay configuration
  hack/run-ci-e2e-test.sh
  pkg/controller/retry/retry.go
  pkg/controller/wellknownlocations/wellknownlocations.go
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachineconfig/windows/windows.go
  test/e2e/create_test.go
  test/e2e/main_test.go
  test/e2e/network_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#38 Bug 1823579: [ci] React to hybrid overlay changes upstream
  README.md
  build/Dockerfile
  build/Dockerfile.ci
  cmd/manager/main.go
  pkg/controller/wellknownlocations/wellknownlocations.go
  pkg/controller/windowsmachineconfig/windows/windows.go
  test/e2e/network_test.go
Labels: approved, bugzilla/valid-bug, lgtm

#33 [ci] Add local dev flags to e2e script
  README.md
  hack/run-ci-e2e-test.sh
  test/e2e/create_test.go
  test/e2e/main_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#39 [ci] Fix failure of e2e hack script
  build/Dockerfile
  build/Dockerfile.ci
Labels: approved, lgtm

#36 Added worker label and windows taint for windows node
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachineconfig/windows/windows.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#37 [wmco]Add cluster configuration checks
  cmd/manager/main.go
  cmd/manager/main_test.go
  deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  hack/unit.sh
  pkg/clusternetwork/config.go
  pkg/clusternetwork/config_test.go
Labels: approved, lgtm

#40 [ci] Add write permission to the image's go folder
  build/Dockerfile
  build/Dockerfile.ci
Labels: approved, lgtm

#41 [wmco] Improve comments, logs and error messages
  hack/run-ci-e2e-test.sh
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachineconfig/tracker/tracker.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  test/e2e/main_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#43 [ci] Fix waits in VM creation failure scenarios
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#44 [ci] Explicitly set GOCACHE environment variable
  build/Dockerfile.ci
Labels: approved, lgtm

#45 [ci] Fix tracker validation test
  go.mod
  go.sum
  pkg/controller/windowsmachineconfig/windows/windows.go
Labels: approved, lgtm

#42 [wmco] Improve error handling
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
Labels: approved, lgtm

#46 [ci] Remove patching of network.operator CR
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm
