Repository openshift/windows-machine-config-operator, pull requests merged in 2020-03, with the labels that each got.

#15 [wmco] WMC controller
  build/Dockerfile
  build/Dockerfile.ci
  cmd/manager/main.go
  deploy/namespace.yaml
  go.mod
  go.sum
  hack/run-ci-e2e-test.sh
  pkg/controller/wellknownlocations/wellknownlocations.go
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachineconfig/windows/windows.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  pkg/internal/wget-ignore-cert.ps1
  test/e2e/main_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, size/XL

#18 [docs] Add testing guidelines
  README.md
Labels: approved, lgtm

#19 Update WMC CRD
  deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml
Labels: approved, lgtm

#23 [wmco] Relax CRD field validation
  deploy/crds/wmc.openshift.io_v1alpha1_windowsmachineconfig_cr.yaml
  deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go
  pkg/controller/wellknownlocations/wellknownlocations.go
Labels: approved, lgtm

#20 [build] Fix operator-sdk image build
  build/Dockerfile
Labels: approved, lgtm

#24 Update README with ssh key information
  README.md
Labels: approved, lgtm

#27 [wmco] Updated payload tree diagram for dockerfiles
  build/Dockerfile
  build/Dockerfile.ci
Labels: approved, lgtm

#26 [docs] Update README for running e2e locally
  README.md
Labels: approved, lgtm

#22 [wmco] Create tracker configmap for Windows VMs
  go.mod
  pkg/controller/windowsmachineconfig/tracker/tracker.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#28 Bug 1813508: Update dockerfile to address buildah COPY bug
  build/Dockerfile
  build/Dockerfile.ci
Labels: approved, bugzilla/valid-bug, lgtm

#25 [wmco] Add validation for fields in the CRD
  deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm
