Repository openshift/windows-machine-config-operator, pull requests merged in 2020-10, with the labels that each got.

#124 [hack/olm.sh] Add build cmd
  hack/common.sh
  hack/olm.sh
Labels: approved, lgtm

#123 [hack] Make wget less verbose
  hack/common.sh
Labels: approved, lgtm

#101 [wmco] Delete Machines with mismatched version annotations
  README.md
  cmd/manager/main.go
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/role.yaml
  hack/run-ci-e2e-test.sh
  pkg/apis/addtoscheme_mapi_v1beta1.go
  pkg/controller/windowsmachine/windowsmachine_controller.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/upgrade_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, ¯\_(ツ)_/¯

#129 [WINC-496] [ci] Add east/west e2e tests through a clusterIP
  go.sum
  test/e2e/network_test.go
Labels: approved, lgtm

#128 Revert "[ci] Run operator deployment on control plane"
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm

#133 [deploy] Use openshift-windows-machine-config-operator namespace
  README.md
  deploy/namespace.yaml
  deploy/olm-catalog/operatorgroup.yaml
  deploy/olm-catalog/subscription.yaml
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/role.yaml
  hack/common.sh
  hack/run-ci-e2e-test.sh
  test/e2e/delete_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#132 [wmco] Fix error output not being shown in logs
  pkg/controller/windowsmachine/windows/connectivity.go
  pkg/controller/windowsmachine/windows/windows.go
Labels: approved, lgtm

#120 Bug 1882526: [wmco] Improve requeuing
  pkg/controller/windowsmachine/windowsmachine_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#125 [test] Use ubi-minimal image for Linux curlers
  test/e2e/network_test.go
Labels: approved, lgtm

#136 [deploy] Change imagePullPolicy to IfNotPresent
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm

#137 [docs] Update README.md, split out HACKING.md
  README.md
  docs/HACKING.md
  docs/setup-hybrid-OVNKubernetes-cluster.md
Labels: approved, lgtm

#121 [hack] add MachineSet creation/deletion script
  README.md
  hack/machineset.sh
Labels: approved, lgtm

#145 Add sebsoto as a reviewer
  OWNERS
Labels: approved, lgtm

#150 [git] Normalize gitmodules URLs
  .gitmodules
Labels: approved, lgtm

#152 [docs] Update cleanup command
  docs/HACKING.md
Labels: approved, lgtm

#153 WINC-460: [ci] Define build_root_image within repo
  .ci-operator.yaml
Labels: approved, lgtm
