Repository openshift/windows-machine-config-operator, pull requests merged in 2020-09, with the labels that each got.

#102 Use downstream kubernetes node binaries
  build/Dockerfile
  build/Dockerfile.ci
  go.mod
  hack/lint-gofmt.sh
  test/e2e/main_test.go
  test/e2e/network_test.go
  vendor/modules.txt
Labels: approved, lgtm

#100 Bug 1860372: [wmco] Remove applying worker label
  README.md
  pkg/controller/windowsmachine/nodeconfig/nodeconfig.go
  test/e2e/create_test.go
  test/e2e/providers/aws/aws.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#93 [controller] Switch to Ignition config spec v3.1
  pkg/controller/windowsmachine/windows/windows.go
  pkg/internal/wget-ignore-cert.ps1
Labels: approved, lgtm

#105 [build] Build CNI plugins from downstream
  build/Dockerfile
  build/Dockerfile.ci
Labels: approved, lgtm

#113 Bug 1875528: Allow reconfiguration of Windows machines after partial configuration failure
  build/Dockerfile
  build/Dockerfile.ci
  pkg/controller/windowsmachine/nodeconfig/init.go
  pkg/controller/windowsmachine/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachine/windows/windows.go
  pkg/controller/windowsmachine/windowsmachine_controller.go
  pkg/internal/wget-ignore-cert.ps1
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#108 [wmco] Watch cloud-private-key secret
  cmd/manager/main.go
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/common.sh
  hack/olm.sh
  hack/run-ci-e2e-test.sh
  pkg/controller/controller.go
  pkg/controller/secret/secret_controller.go
  pkg/controller/secrets/secrets.go
  pkg/controller/signer/signer.go
  pkg/controller/wellknownlocations/wellknownlocations.go
  pkg/controller/windowsmachine/windowsmachine_controller.go
  test/e2e/create_test.go
  test/e2e/main_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#117 [docs] Fix README operator-sdk and MachineSet refs
  README.md
Labels: approved, lgtm

#118 [ci] Add write permissions to WMCO repo directory
  build/Dockerfile.ci
Labels: approved, lgtm

#119 [wmco] Remove explicit use of --skip-deletion
  hack/run-ci-e2e-test.sh
  test/e2e/main_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#110 [test] Remove passing of SSH Key Pair env var
  hack/run-ci-e2e-test.sh
  test/e2e/main_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/cloudprovider.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#122 [ci] Run operator deployment on control plane
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm

#104 [wmco] Run hybrid overlay as a Windows service
  pkg/controller/windowsmachine/windows/service.go
  pkg/controller/windowsmachine/windows/windows.go
Labels: approved, lgtm
