Repository openshift/windows-machine-config-operator, pull requests merged in 2020-02, with the labels that each got.

#1 [wmco] Barebone WMCO initialization
  .gitignore
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  deploy/crds/wmc.openshift.io_v1alpha1_windowsmachineconfig_cr.yaml
  deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_wmc_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/wmc/group.go
  pkg/apis/wmc/v1alpha1/doc.go
  pkg/apis/wmc/v1alpha1/register.go
  pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go
  pkg/apis/wmc/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_windowsmachineconfig.go
  pkg/controller/controller.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  tools.go
  version/version.go
Labels: lgtm, size/XXL

#2 Update .gitignore for GoLand
  .gitignore
Labels: lgtm, size/XS

#3 Update operator Dockerfile with payload
  README.md
  build/Dockerfile
Labels: lgtm, size/M

#5 Create OWNERS file
  OWNERS
Labels: lgtm, size/XS

#4 [build] Add Makefile
  Makefile
  build/build.sh
  hack/lint-gofmt.sh
  hack/run-ci-e2e-test.sh
Labels: lgtm, size/M

#6 [build] Add Dockerfile for ci
  build/Dockerfile.ci
Labels: lgtm, size/L

#7 [build] Use golang 1.13 for builder
  build/Dockerfile
  build/Dockerfile.ci
Labels: lgtm, size/S

#8 [build] Add missing mkdir /download/cni-plugins/
  build/Dockerfile
  build/Dockerfile.ci
Labels: lgtm, size/XS

#9 [build] Add workaround for CI enforcing vendoring
  build/build.sh
Labels: lgtm, size/XS

#10 [build] Account for GOFLAGS not being set
  build/build.sh
Labels: lgtm, size/XS

#11 [build] Fix building of WMCO in Dockerfile.ci
  build/Dockerfile.ci
Labels: lgtm, size/XS

#12 [build] Add target for running unit tests
  Makefile
  hack/unit.sh
Labels: lgtm, size/S

#14 [build] Fix make clean
  Makefile
  build/build.sh
Labels: approved, lgtm, size/S
