Repository openshift/windows-machine-config-operator, pull requests merged in 2020-05, with the labels that each got.

#48 Bump operator SDK & WNI
  README.md
  go.mod
  go.sum
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#49 [ci] Ensure WMC CRD is up to date in lint job
  Makefile
  hack/common.sh
  hack/lint-generate-crds.sh
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#35 Keep track of operator status in WMC CR
  deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  deploy/olm-catalog/windows-machine-config-operator/0.0.0/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  pkg/apis/wmc/v1alpha1/conditions.go
  pkg/apis/wmc/v1alpha1/conditions_test.go
  pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go
  pkg/apis/wmc/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/windowsmachineconfig/status.go
  pkg/controller/windowsmachineconfig/status_test.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/status_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#47 [wmco] Generate cluster address from config
  README.md
  deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml
  deploy/operator.yaml
  hack/run-ci-e2e-test.sh
  pkg/controller/windowsmachineconfig/nodeconfig/init.go
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig_test.go
  pkg/controller/windowsmachineconfig/windows/windows.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
Labels: approved, lgtm

#52 Bug 1819227: [wmco] Remove unnecessary watching of Pods
  deploy/olm-catalog/windows-machine-config-operator/0.0.0/windows-machine-config-operator.v0.0.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#53 Bug 1835166: [wmco] fix validation for replicas
  deploy/crds/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  pkg/apis/wmc/v1alpha1/windowsmachineconfig_types.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/status_test.go
  test/e2e/validation_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#51 [wmco] Fix restart
  hack/run-ci-e2e-test.sh
  pkg/controller/windowsmachineconfig/tracker.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/main_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#57 [wmco] fix formatting of errors.wrap messages
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachineconfig/tracker.go
  pkg/controller/windowsmachineconfig/windows/windows.go
Labels: approved, lgtm

#50 [wmco] Configure CNI on nodes
  README.md
  build/Dockerfile
  build/Dockerfile.ci
  cmd/manager/main.go
  hack/run-ci-e2e-test.sh
  pkg/clusternetwork/config.go
  pkg/clusternetwork/config_test.go
  pkg/controller/controller.go
  pkg/controller/wellknownlocations/wellknownlocations.go
  pkg/controller/windowsmachineconfig/nodeconfig/network.go
  pkg/controller/windowsmachineconfig/nodeconfig/network_test.go
  pkg/controller/windowsmachineconfig/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachineconfig/tracker.go
  pkg/controller/windowsmachineconfig/windows/windows.go
  pkg/controller/windowsmachineconfig/windowsmachineconfig_controller.go
  pkg/internal/cni-conf-template.json
  test/e2e/main_test.go
  test/e2e/network_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#59 [wmco] Bump wni version to reflect latest changes
  go.mod
  go.sum
Labels: approved, lgtm

#60 Bug 1840504: Copy cni-conf-template.json failed
  build/Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#55 [docs] introduce contribution guidelines
  CONTRIBUTION.md
  images/PR-workflow.png
Labels: approved, lgtm

#54 Bug 1837936: Failed to create wmco catalogsource
  README.md
  bundle.Dockerfile
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/olm-catalog/windows-machine-config-operator/manifests/wmc.openshift.io_windowsmachineconfigs_crd.yaml
  deploy/olm-catalog/windows-machine-config-operator/metadata/annotations.yaml
  hack/common.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
