Repository openshift/windows-machine-config-operator, pull requests merged in 2021-08, with the labels that each got.

#499 WINC-581: Approve CSRs of BYOH instances
  PROJECT
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/certificatesigningrequests_controller.go
  controllers/configmap_controller.go
  controllers/configmap_controller_test.go
  controllers/secret_controller.go
  docs/csr_approval_mechanism.md
  main.go
  pkg/csr/csr.go
  pkg/csr/csr_test.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
  pkg/wiparser/wiparser_test.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#549 WINC-649: [wmco] Change BYOH annotation to a label
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/secret_controller.go
  test/e2e/create_test.go
Labels: approved, lgtm

#562 WINC-639: [docs] Add key rotation documentation
  README.md
Labels: approved, lgtm

#553 WINC-643: Normalize BYOH and Machine logs and events
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/windowsmachine_controller.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
Labels: approved, lgtm

#539 [docs] Add BYOH pre-requisites
  README.md
  docs/byoh-instance-pre-requisites.md
Labels: approved, lgtm

#545 [docs] Update vSphere machineSet requirement
  README.md
Labels: approved, lgtm

#544 WINC-610: Introduce vSphere Template as golden image
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#590 [OWNERS] Remove ravisantoshgudimetla from approvers
  OWNERS
Labels: approved, lgtm

#574 WINC-648: [wmco] Remove HNS networks in BYOH deconfiguration
  pkg/windows/windows.go
  test/e2e/delete_test.go
  test/e2e/reconfigure_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#572 [wmco] Remove stuttering from instances pkg
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/windowsmachine_controller.go
  pkg/csr/csr.go
  pkg/csr/csr_test.go
  pkg/instance/instance.go
  pkg/instance/instance_test.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
  pkg/wiparser/wiparser_test.go
Labels: approved, lgtm

#602 Bug 1992428: [wmco] Capture delete event for BYOH Windows nodes
  controllers/controllers.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#571 Bug 1991739: [wmco] Fix metrics endpoint on machine not found
  controllers/windowsmachine_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#515 [docs] Update scripts and docs for vSphere golden image
  docs/images/vcenter-vm-to-template.png
  docs/unattend.xml
  docs/vsphere-golden-image.md
  docs/vsphere_ci/README.md
  docs/vsphere_ci/build.json
  docs/vsphere_ci/images/VMConversion.png
  docs/vsphere_ci/scripts/autounattend.xml
  docs/vsphere_ci/scripts/configure-vm-tools.ps1
  docs/vsphere_ci/scripts/install-docker.ps1
Labels: approved, lgtm

#612 [windows] Improve connectivity.run()
  pkg/windows/connectivity.go
Labels: approved, lgtm

#603 [wmco] Fix issues with removing HNS networks
  pkg/windows/windows.go
Labels: approved, lgtm

#580 Prep for 3.1.0 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#623 [vendor] Stop unnecessarily replacing libraries
  go.mod
  go.sum
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusteroperator.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_00_cluster-version-operator_01_clusterversion.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_build.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_console.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_dns.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_image.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_infrastructure.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_ingress.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_network.crd.yaml
  vendor/github.com/openshift/api/config/v1/0000_10_config-operator_01_scheduler.crd.yaml
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_feature.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_ingress.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_scheduling.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/operator/v1/0000_10_config-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_12_etcd-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_20_kube-apiserver-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-controller-manager-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_25_kube-scheduler-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_40_cloud-credential-operator_00_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_cluster-authentication-operator_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_50_ingress-operator_00-ingresscontroller.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_cluster-network-operator_01_crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_console-operator.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_70_dns-operator_00-custom-resource-definition.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml
  vendor/github.com/openshift/api/operator/v1/0000_90_cluster_csi_driver_01_config.crd.yaml-patch
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_authentication.go
  vendor/github.com/openshift/api/operator/v1/types_cloudcredential.go
  vendor/github.com/openshift/api/operator/v1/types_config.go
  vendor/github.com/openshift/api/operator/v1/types_console.go
  vendor/github.com/openshift/api/operator/v1/types_csi_cluster_driver.go
  vendor/github.com/openshift/api/operator/v1/types_dns.go
  vendor/github.com/openshift/api/operator/v1/types_etcd.go
  vendor/github.com/openshift/api/operator/v1/types_ingress.go
  vendor/github.com/openshift/api/operator/v1/types_network.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/modules.txt
Labels: approved, lgtm

#626 [release-4.8] Prep for 3.1.0 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#628 WINC-645: [controllers] Handle generic events
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/windowsmachine_controller.go
Labels: approved, lgtm

#642 [wmco] Ensure HNS networks are removed
  pkg/windows/windows.go
Labels: approved, lgtm

#627 [hack] Update run-ci-e2e-test.sh usage message
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm
