Repository openshift/windows-machine-config-operator, pull requests merged in 2021-11, with the labels that each got.

#781 Replace git with http URL in .gitmodules
  .gitmodules
Labels: approved, lgtm

#780 Prep for 5.0.0 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#786 [community-4.7] Replace git with https URL in .gitmodules
  .gitmodules
Labels: approved, lgtm

#776 Bug 2005360: Lookup nodes via IPv4 address
  pkg/instance/instance.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_test.go
  pkg/wiparser/wiparser.go
  pkg/wiparser/wiparser_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#785 [release-4.7] Replace git with https URL in .gitmodules
  .gitmodules
Labels: approved, lgtm

#778 [release-4.9] WINC-571: [wmco] Prevent OLM upgrades when operator is busy
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/certificatesigningrequests_controller.go
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  go.mod
  go.sum
  main.go
  pkg/condition/condition.go
  pkg/condition/condition_test.go
  pkg/retry/retry.go
  test/e2e/clusterinfo/openshift.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/validation_test.go
  vendor/github.com/operator-framework/api/LICENSE
  vendor/github.com/operator-framework/api/pkg/operators/v2/doc.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/groupversion_info.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/operatorcondition_types.go
  vendor/github.com/operator-framework/api/pkg/operators/v2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm

#793 [docs] Standardize name of user data secret
  README.md
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#799 [release-4.9] Prep for 4.0.1 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm

#802 Use more appropriate sample domain name for docs
  README.md
Labels: approved, lgtm

#807 [Dockerfile] Update index image version label to 4.10
  bundle.Dockerfile
Labels: approved, lgtm

#801 [release-4.8] Prep for 3.1.1 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm

#798 [docs] Update SAM verbiage in project volume doc
  docs/projected-volume.md
Labels: approved, lgtm

#813 [e2e] Use powershell:lts-nanoserver-20h2 image
  test/e2e/network_test.go
Labels: approved, lgtm

#817 [wmco] Re-arrange import and add missing spaces
  pkg/cluster/config.go
  pkg/cluster/config_test.go
  pkg/crypto/crypto_test.go
Labels: approved, lgtm

#777 Bug 1994859: Get and pass Cluster DNS to wmcb.exe
  go.mod
  go.sum
  pkg/cluster/config.go
  pkg/cluster/config_test.go
  pkg/csr/csr.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/network_test.go
  vendor/github.com/apparentlymart/go-cidr/LICENSE
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#827 [hack] Remove stale OSDK test code
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#828 [docs] Minor fixes to HACKING.md
  docs/HACKING.md
Labels: approved, lgtm
