Repository openshift/windows-machine-config-operator, pull requests merged in 2021-02, with the labels that each got.

#263 WINC-565: [release-4.6] [wmco] Relax k8s version strict dependency
  cmd/manager/main.go
  cmd/manager/main_test.go
  go.mod
  vendor/golang.org/x/mod/LICENSE
  vendor/golang.org/x/mod/PATENTS
  vendor/golang.org/x/mod/semver/semver.go
  vendor/modules.txt
Labels: approved, lgtm

#265 [release-4.6][wmco] Prep for 1.0.3 release
  bundle.Dockerfile
  hack/common.sh
Labels: approved, lgtm

#262 WINC-565: [wmco] Relax k8s version strict dependency
  go.mod
  pkg/cluster/config.go
  pkg/cluster/config_test.go
  vendor/modules.txt
Labels: approved, lgtm

#266 [deploy] Add skipRange to csv for 2.0.0 release
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#261 [hack] Modify ami_date for machineset.sh script
  hack/machineset.sh
Labels: approved, lgtm

#270 Revert "Switch build base image to Red Hat hosted image"
  build/Dockerfile
Labels: approved, lgtm

#280 WINC-565: [community-4.7][wmco] Relax k8s version strict dependency
  go.mod
  pkg/cluster/config.go
  pkg/cluster/config_test.go
  vendor/modules.txt
Labels: approved, lgtm

#281 WINC-565: [community-4.6][wmco] Relax k8s version strict dependency
  cmd/manager/main.go
  cmd/manager/main_test.go
  go.mod
  vendor/golang.org/x/mod/LICENSE
  vendor/golang.org/x/mod/PATENTS
  vendor/golang.org/x/mod/semver/semver.go
  vendor/modules.txt
Labels: approved, lgtm

#283 [release-4.6] [deploy] Update Operator capability to 'Seamless Upgrades'
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#271 WINC-533: [docs] Build vSphere Windows VM images
  docs/vsphere-prerequisites.md
  docs/vsphere_ci/README.md
  docs/vsphere_ci/build.json
  docs/vsphere_ci/images/VMConversion.png
  docs/vsphere_ci/scripts/authorized_keys
  docs/vsphere_ci/scripts/autounattend.xml
  docs/vsphere_ci/scripts/install-docker.ps1
  docs/vsphere_ci/scripts/install-vm-tools.cmd
  docs/vsphere_ci/scripts/powershell.ps1
  docs/vsphere_ci/scripts/win-updates.ps1
Labels: approved, lgtm

#284 [Community-4.7] [deploy] Update Operator capability to 'Seamless Upgrades'
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#272 WINC-574: [ci] Introduce retries for WMCO deployment
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#273 Update powershell.ps1
  docs/powershell.ps1
  docs/vsphere-prerequisites.md
Labels: approved, lgtm

#282 [deploy] Update operator capability to 'Seamless upgrades'
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#288 WINC-574: [community-4.6]][ci] Introduce retries for WMCO deployment
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#286 WINC-574: [release-4.6][ci] Introduce retries for WMCO deployment
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#274 [wmco] Remove constant for metrics resources name
  pkg/controller/windowsmachine/metrics/metrics.go
Labels: approved, lgtm

#287 WINC-574: [release-4.7][ci] Introduce retries for WMCO deployment
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#289 WINC-574: [community-4.7][ci] Introduce retries for WMCO deployment
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#295 [release-4.7][test] Introduce CloudProvider.GetType()
  test/e2e/create_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#285 [test] Fix e2e tests for vSphere
  test/e2e/create_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#291 [release-4.7] [deploy] Update operator capability to 'Seamless upgrades'
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#294 [community-4.6][wmco] Remove constant for metrics resources name
  pkg/controller/windowsmachine/metrics/metrics.go
Labels: approved, lgtm

#301 [test] Don't run all tests on all platforms
  test/e2e/create_test.go
  test/e2e/reconfigure_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#296 [community-4.7] Add pubkey annotation to Windows nodes
  pkg/controller/secret/secret_controller.go
  pkg/controller/windowsmachine/nodeconfig/nodeconfig.go
  pkg/controller/windowsmachine/windowsmachine_controller.go
  test/e2e/create_test.go
  test/e2e/secrets_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#300 [community-4.7][wmco] Delete existing service monitor object on WMCO restart
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/windowsmachine/metrics/metrics.go
Labels: approved, lgtm

#304 [community-4.7][test] Introduce CloudProvider.GetType()
  test/e2e/create_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#306 [hack] Move error-exit to common.sh
  hack/common.sh
  hack/machineset.sh
Labels: approved, lgtm

#290 [docs] Remove AWS describe-image command
  docs/machineset-aws.md
  hack/machineset.sh
Labels: approved, lgtm

#293 [community-4.7][wmco] Remove constant for metrics resources name
  pkg/controller/windowsmachine/metrics/metrics.go
Labels: approved, lgtm

#302 WINC-501: [wmco] Reorganize pkg directory for OSDK 1.0
  apis/addtoscheme_mapi_v1beta1.go
  apis/apis.go
  build/Dockerfile
  build/Dockerfile.ci
  cmd/manager/main.go
  controllers/add_secret.go
  controllers/add_windowsmachine.go
  controllers/controller.go
  controllers/secret/secret_controller.go
  controllers/windowsmachine/windowsmachine_controller.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  pkg/nodeconfig/init.go
  pkg/nodeconfig/network.go
  pkg/nodeconfig/network_test.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/nodeconfig_test.go
  pkg/nodeconfig/payload/payload.go
  pkg/retry/retry.go
  pkg/secrets/secrets.go
  pkg/signer/signer.go
  pkg/windows/connectivity.go
  pkg/windows/service.go
  pkg/windows/windows.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.mod
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/alertmanager.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/generated_expansion.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/podmonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/probe.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheus.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheusrule.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/servicemonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/thanosruler.go
  vendor/modules.txt
Labels: approved, lgtm

#297 small updates to vsphere readme
  docs/vsphere-prerequisites.md
Labels: approved, lgtm

#310 [community-4.7] WINC-501: [wmco] Reorganize pkg directory for OSDK 1.0
  apis/addtoscheme_mapi_v1beta1.go
  apis/apis.go
  build/Dockerfile
  build/Dockerfile.ci
  cmd/manager/main.go
  controllers/add_secret.go
  controllers/add_windowsmachine.go
  controllers/controller.go
  controllers/secret/secret_controller.go
  controllers/windowsmachine/windowsmachine_controller.go
  go.mod
  go.sum
  pkg/metrics/metrics.go
  pkg/nodeconfig/init.go
  pkg/nodeconfig/network.go
  pkg/nodeconfig/network_test.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/nodeconfig_test.go
  pkg/nodeconfig/payload/payload.go
  pkg/retry/retry.go
  pkg/secrets/secrets.go
  pkg/signer/signer.go
  pkg/windows/connectivity.go
  pkg/windows/service.go
  pkg/windows/windows.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.mod
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/go.sum
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/alertmanager_config_types.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/LICENSE
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/scheme/register.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/alertmanager.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/doc.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/generated_expansion.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/monitoring_client.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/podmonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/probe.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheus.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/prometheusrule.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/servicemonitor.go
  vendor/github.com/prometheus-operator/prometheus-operator/pkg/client/versioned/typed/monitoring/v1/thanosruler.go
  vendor/modules.txt
Labels: approved, lgtm

#305 [test] Don't assume vSphere network name
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#309 [community-4.7][hack] Move error-exit to common.sh
  hack/common.sh
  hack/machineset.sh
Labels: approved, lgtm

#312 Bug 1929579: [wmco] Fix issue with dereferencing nil signer
  controllers/windowsmachine/windowsmachine_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#313 Bug 1929794: [wmco] Fix issue with dereferencing nil signer
  pkg/controller/windowsmachine/windowsmachine_controller.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#252 Bug 1905280: [wmco] Delete existing service monitor object on WMCO restart
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/metrics/metrics.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, qe-approved

#299 [community-4.6][wmco] Delete existing service monitor object on WMCO restart
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/windowsmachine/metrics/metrics.go
Labels: approved, lgtm

#315 Bug 1930184: Fix formatting and description for WMCO 2.0.0
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#316 Bug 1930257: Fix formatting and description for WMCO 2.0.0
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#321 WINC-555: [test] Use Windows Server 20H2 for Azure e2e tests
  test/e2e/network_test.go
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm
