Repository openshift/windows-machine-config-operator, pull requests merged in 2021-09, with the labels that each got.

#649 [config] Update the k8s version in the CSV
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#630 Bug 1991282: [wmco] Set WMCB node-ip arg appropriately for BYOH
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/windowsmachine_controller.go
  pkg/instance/instance.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#655 Bug 1995684: Validate and perform DNS lookup on Windows instance network address
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeutil/nodeutil.go
  pkg/nodeutil/nodeutil_test.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-low

#656 [wmco] Fix incorrect error formatting
  pkg/windows/windows.go
Labels: approved, lgtm

#645 Bug 1996615: Add pods eviction permission and logging for drainer helper
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/configmap_controller.go
  pkg/nodeconfig/nodeconfig.go
  test/e2e/network_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-urgent

#662 WINC-644: [wmco] Remove "--feature-gates=IPv6DualStack=false"
  pkg/windows/windows.go
Labels: approved, lgtm

#667 [docs] SSH shell pre-requisite
  docs/byoh-instance-pre-requisites.md
Labels: approved, lgtm

#670 [hack] Stop using IMAGE_FORMAT in run-ci-e2e-test
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#664 Bug 2001547: Validate instance addresses before deconfiguring BYOH nodes
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/windowsmachine_controller.go
  pkg/instance/instance.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeutil/nodeutil.go
  pkg/nodeutil/nodeutil_test.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
  pkg/wiparser/wiparser_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high

#668 Bug 2002961: Prevent error loop when a CSR is queued and then approved externally
  controllers/certificatesigningrequests_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#669 [vsphere] create machineset spec based on machineset spec created at install time
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#685 Prep for 4.0.0 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#686 [doc] Document pre-requsite for PTR records
  docs/byoh-instance-pre-requisites.md
Labels: approved, lgtm

#698 [windows] Rename getSourceVIP()
  pkg/windows/windows.go
Labels: approved, lgtm

#683 [docs] update HACKING.md with missing pre-requisites
  docs/HACKING.md
Labels: approved, lgtm

#704 [OWNERS] Add mansikulkarni96 as a reviewer
  OWNERS
Labels: approved, lgtm

#692 [docs][vsphere-ci] Update VMware Tools to v11.3.0
  docs/vsphere_ci/build.json
Labels: approved, lgtm

#705 [windows] Add dependencies to Windows service struct
  pkg/windows/service.go
  pkg/windows/windows.go
Labels: approved, lgtm

#674 [e2e] Rollback node affinity for BYOH label
  test/e2e/network_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#676 [wmco] Enable pods eviction logging
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm

#706 Bug 2008601: Fix delete event subscription
  controllers/windowsmachine_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#538 [release-4.7] Bug 1995340: Fix metrics endpoint + Update golden image + IBM cluster support
  controllers/windowsmachine_controller.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#675 Bug 1992841: Do not react to Windows Node deletion
  controllers/windowsmachine_controller.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
