Repository openshift/windows-machine-config-operator, pull requests merged in 2022-08, with the labels that each got.

#1156 [docs] Document WMCO proxy limitation
  README.md
Labels: approved, lgtm

#1152 WINC-848: Manage Windows exporter with WICD
  controllers/configmap_controller.go
  pkg/windows/windows.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#1157 WINC-737: Start hybrid-overlay with WICD
  controllers/configmap_controller.go
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  pkg/windows/windows.go
Labels: approved, lgtm

#1165 [release-4.10][docs] DeploymentConfig limitation
  README.md
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1166 [wicd] Restructure Windows service interaction
  cmd/daemon/bootstrap.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/fake/manager.go
  pkg/daemon/fake/manager_test.go
  pkg/daemon/fake/winsvc.go
  pkg/daemon/fake/winsvc_test.go
  pkg/daemon/manager/manager.go
  pkg/daemon/winsvc/winsvc.go
Labels: approved, lgtm

#1169 Minor ConfigMap controller improvements
  controllers/configmap_controller.go
Labels: approved, lgtm

#1168 Log WMCO timestamps in RFC3339 format
  cmd/operator/main.go
  go.mod
Labels: approved, lgtm

#1151 WINC-823: Test generated community manifests in WMCO e2e
  Makefile
  hack/community/csv/description.md
  hack/community/generate.sh
  hack/community/readme.md
Labels: approved, lgtm

#1172 Update AWS machineset docs
  docs/machineset-aws.md
Labels: approved, lgtm

#1170 WINC-814: Add GCP to machineset.sh
  hack/machineset.sh
Labels: approved, lgtm

#1176 [docs] Add Windows node limitations
  README.md
Labels: approved, lgtm

#1180 [release-4.7][docs] DeploymentConfig limitation
  README.md
  deploy/olm-catalog/windows-machine-config-operator/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: do-not-merge/hold, approved, lgtm

#1178 [release-4.9][docs] DeploymentConfig limitation
  README.md
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1174 [docs] Limitation to access secure registry images
  README.md
Labels: approved, lgtm

#1186 [community-4.10] WINC-823: Test generated community manifests in WMCO e2e
  Makefile
  hack/community/csv/description.md
  hack/community/generate.sh
  hack/community/readme.md
Labels: approved, lgtm

#1188 [docs] Clarify storage support
  README.md
Labels: approved, lgtm

#1179 [release-4.8][docs] DeploymentConfig limitation
  README.md
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1191 [docs] OCP Bugzilla to Jira adoption
  CONTRIBUTION.md
Labels: approved, lgtm

#1190 Update issue templates
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/rfe.yaml
Labels: approved, lgtm

#1192 Refactor providers package
  test/e2e/clusterinfo/constants.go
  test/e2e/clusterinfo/openshift.go
  test/e2e/main_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/machineset/machineset.go
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#1189 [winsvc] Wait for service state changes
  pkg/daemon/winsvc/winsvc.go
  pkg/retry/retry.go
Labels: approved, lgtm

#1154 WINC-718: WICD cleanup command
  cmd/daemon/bootstrap.go
  cmd/daemon/cleanup.go
  controllers/configmap_controller.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/cleanup/cleanup_test.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/fake/manager.go
  pkg/daemon/fake/manager_test.go
  pkg/daemon/manager/manager.go
  pkg/servicescm/servicescm.go
Labels: approved, lgtm

#1202 [release-4.11] Revert "[e2e] unblock aws CI failure"
  test/e2e/providers/aws/aws.go
Labels: approved, lgtm

#1209 Fix issue templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/rfe.yml
Labels: approved, lgtm

#1155 WINC-823: Test generated community manifests in WMCO e2e Followup
  hack/common.sh
  hack/community/generate.sh
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#1214 Make log test more resilient
  hack/run-ci-e2e-test.sh
  test/e2e/logs_test.go
Labels: approved, lgtm

#1215 Fix issue template yaml syntax
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/rfe.yml
Labels: approved, lgtm

#1197 WINC-815: Add support for Windows Server 2022 on GCP clusters
  README.md
  controllers/windowsmachine_controller.go
  docs/HACKING.md
  docs/machineset-gcp.md
  docs/wmco-prerequisites.md
  pkg/secrets/secrets.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/machineset/machineset.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#1213 Bug 2074289: Update x/crypto
  go.mod
  go.sum
  vendor/golang.org/x/crypto/AUTHORS
  vendor/golang.org/x/crypto/CONTRIBUTORS
  vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/internal/alias/alias.go
  vendor/golang.org/x/crypto/internal/alias/alias_purego.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1221 [release-4.11] OCPBUGS-671: Update x/crypto
  go.mod
  go.sum
  vendor/golang.org/x/crypto/AUTHORS
  vendor/golang.org/x/crypto/CONTRIBUTORS
  vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/internal/field/fe_amd64.go
  vendor/golang.org/x/crypto/internal/alias/alias.go
  vendor/golang.org/x/crypto/internal/alias/alias_purego.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate
