Repository openshift/windows-machine-config-operator, pull requests merged in 2022-05, with the labels that each got.

#1045 Bug 2070892: Skip node addresses without PTR record during instance de-configuration
  controllers/configmap_controller.go
  controllers/configmap_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1030 [e2e] Initialize OpenShift client's cache
  test/e2e/clusterinfo/openshift.go
Labels: approved, lgtm

#1044 WINC-803: Update correct WMCO subscription info
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved

#1055 [community-4.10] OCPBUGSM-42819: Skip node addresses without PTR record during instance de-configuration
  controllers/configmap_controller.go
  controllers/configmap_controller_test.go
Labels: approved, lgtm

#1057 [release-4.9] [bundle] Update correct WMCO subscription info
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm

#1054 [release-4.10] Bug 2081825: Skip node addresses without PTR record during instance de-configuration
  controllers/configmap_controller.go
  controllers/configmap_controller_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#1052 WINC-817: Create vSphere golden image without Docker installed
  README.md
  docs/vsphere-golden-image.md
  docs/vsphere-prerequisites.md
  docs/vsphere_ci/README.md
  docs/vsphere_ci/build.json
  docs/vsphere_ci/scripts/autounattend.xml
  docs/vsphere_ci/scripts/install-docker.ps1
  docs/vsphere_ci/scripts/install-kb5012637.ps1
  docs/wmco-prerequisites.md
  hack/machineset.sh
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#1035 WINC-755: Use patched Windows Server 2022 golden image in vSphere CI
  README.md
  docs/vsphere-golden-image.md
  docs/vsphere-prerequisites.md
  docs/vsphere_ci/README.md
  docs/vsphere_ci/build.json
  docs/vsphere_ci/scripts/autounattend.xml
  docs/vsphere_ci/scripts/install-kb5012637.ps1
  docs/wmco-prerequisites.md
  hack/machineset.sh
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#1058 [docs] clean up Docker specific debug information
  docs/TROUBLESHOOTING.md
  docs/machineset-aws.md
Labels: approved

#1060 WINC-819: Enable required Windows feature for Containers
  docs/vsphere-golden-image.md
  docs/vsphere_ci/scripts/autounattend.xml
  pkg/windows/windows.go
Labels: approved, lgtm

#1061 WINC-717: Initial WICD controller implementation
  cmd/daemon/controller.go
  cmd/daemon/main.go
  hack/wicd-unit.sh
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/winsvc/winsvc.go
  pkg/daemon/winsvc/winsvc_test.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
Labels: approved, lgtm

#1046 Document BYOH static IP limitation
  docs/byoh-instance-pre-requisites.md
Labels: approved, lgtm

#1067 Correct Windows service start/stop behavior
  pkg/daemon/controller/controller.go
  pkg/daemon/winsvc/winsvc.go
  pkg/daemon/winsvc/winsvc_test.go
Labels: approved, lgtm

#1071 Enable generation of custom service CMs
  controllers/configmap_controller.go
  pkg/servicescm/servicescm.go
  pkg/servicescm/servicescm_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#1069 Better WICD dependency handling
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/winsvc/winsvc.go
  pkg/daemon/winsvc/winsvc_test.go
Labels: approved, lgtm

#1075 WINC-821 : [build] Bump to go 1.18
  .ci-operator.yaml
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  go.mod
  go.sum
  hack/lint-gofmt.sh
Labels: approved, lgtm

#1073 WINC-825: WICD reacts to Node events
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/servicescm/servicescm.go
  pkg/servicescm/servicescm_test.go
Labels: approved, lgtm
