Repository openshift/windows-machine-config-operator, pull requests merged in 2022-01, with the labels that each got.

#844 Bug 2032048: Fix CVO override and retry Update of CSRs approval status
  controllers/certificatesigningrequests_controller.go
  pkg/csr/csr.go
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#861 [e2e] Improve CVO override creation and patching
  test/e2e/create_test.go
Labels: approved, lgtm

#839 [release-4.8] WINC-678: Upgrade to Operator SDK 1.15.0
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/tests/scorecard/config.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role.yaml
  docs/HACKING.md
  go.mod
  go.sum
  hack/common.sh
  vendor/k8s.io/apimachinery/third_party/forked/golang/LICENSE
  vendor/k8s.io/apimachinery/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/third_party/forked/golang/LICENSE
  vendor/k8s.io/client-go/third_party/forked/golang/PATENTS
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/go.mod
  vendor/sigs.k8s.io/controller-runtime/go.sum
  vendor/sigs.k8s.io/controller-runtime/pkg/builder/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go
  vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/metadata_infomer_wrapper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/apiutil/apimachinery.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go
  vendor/sigs.k8s.io/controller-runtime/pkg/manager/internal.go
  vendor/sigs.k8s.io/controller-runtime/pkg/metrics/listener.go
  vendor/sigs.k8s.io/controller-runtime/pkg/source/source.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/defaulter_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/admission/validator_custom.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/alias.go
  vendor/sigs.k8s.io/controller-runtime/pkg/webhook/server.go
Labels: approved, lgtm

#866 Prep for 1.0.6 release
  hack/common.sh
Labels: approved, lgtm

#867 Prep for 2.0.4 release
  hack/common.sh
Labels: approved, lgtm

#869 [e2e] Scale down CVO when testing BYOH CSRs
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#803 [config] Add ServiceAccount manifest
  config/rbac/kustomization.yaml
  config/rbac/service_account.yaml
Labels: approved, lgtm

#873 Revert "[e2e] Scale down CVO when testing BYOH CSRs"
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#872 WINC-617: Specify container runtime flag and transfer containerd files
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/windowsmachine_controller.go
  main.go
  pkg/csr/csr.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/payload/payload.go
  pkg/windows/windows.go
  test/e2e/delete_test.go
Labels: approved, lgtm

#863 [e2e] Remove DNS test for invalid URL
  test/e2e/network_test.go
Labels: approved, lgtm

#865 WINC-607: [e2e] Modularize BYOH configuration test
  test/e2e/create_test.go
Labels: approved, lgtm

#879 [docs] Remove Windows server 2004 from supported version
  docs/wmco-prerequisites.md
Labels: approved

#877 [community 4.8] OCPBUGSM-36947: Get and pass Cluster DNS to wmcb.exe
  go.mod
  go.sum
  pkg/cluster/config.go
  pkg/cluster/config_test.go
  pkg/csr/csr.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/network_test.go
  vendor/github.com/apparentlymart/go-cidr/LICENSE
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/modules.txt
Labels: approved, lgtm

#858 WINC-607: Add support for platform=none in e2e test suite
  Makefile
  docs/HACKING.md
  docs/vsphere_ci/platform-none/README.md
  docs/vsphere_ci/platform-none/create-ptr-records.sh
  hack/common.sh
  hack/run-ci-e2e-test.sh
  test/e2e/create_test.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/none/none.go
Labels: approved, lgtm

#855 [release-4.9] Bug 2020350: Get and pass Cluster DNS to wmcb.exe
  go.mod
  go.sum
  pkg/cluster/config.go
  pkg/cluster/config_test.go
  pkg/csr/csr.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/network_test.go
  vendor/github.com/apparentlymart/go-cidr/LICENSE
  vendor/github.com/apparentlymart/go-cidr/cidr/cidr.go
  vendor/github.com/apparentlymart/go-cidr/cidr/wrangling.go
  vendor/modules.txt
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-high
