Repository openshift/windows-machine-config-operator, pull requests merged in 2022-11, with the labels that each got.

#1272 Remove kubelet version test
  test/e2e/validation_test.go
Labels: approved, lgtm

#1273 WINC-739: Azure node manager added to services ConfigMap
  controllers/configmap_controller.go
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  pkg/windows/windows.go
  test/e2e/create_test.go
Labels: approved, lgtm

#1258 WINC-888: Use platform-specific tags in userData
  cmd/operator/main.go
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  pkg/secrets/secrets.go
  pkg/secrets/secrets_test.go
Labels: approved, lgtm

#1312 [windows] Remove unused const & fix comments
  pkg/windows/windows.go
Labels: approved, lgtm

#1303 [release-4.9] [windows] Increase kubelet verbosity in debug
  pkg/windows/windows.go
Labels: approved, lgtm

#1284 OCPBUGS-2028: Set kubelet hostname for GCP platform
  build/Dockerfile
  build/Dockerfile.ci
  build/Dockerfile.wmco
  cmd/operator/main.go
  pkg/internal/gcp-get-hostname.ps1
  pkg/nodeconfig/payload/payload.go
  pkg/services/services.go
  pkg/services/services_test.go
  pkg/windows/windows.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate

#1306 WINC-927: Enable stopping a service with dependent services
  hack/run-ci-e2e-test.sh
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/fake/manager.go
  pkg/daemon/fake/manager_test.go
  pkg/daemon/fake/winsvc.go
  pkg/daemon/fake/winsvc_test.go
  pkg/daemon/manager/manager.go
  pkg/daemon/winsvc/winsvc.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#1323 [services] Use IMDSv1 to get hostname in AWS
  pkg/services/services.go
  pkg/services/services_test.go
Labels: approved, lgtm

#1316 OCPBUGS-1513: Fix check for Windows Defender
  pkg/windows/windows.go
  test/e2e/create_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1331 Add merge blocker issue template
  .github/ISSUE_TEMPLATE/merge-blocker.yml
Labels: approved, lgtm

#1335 Fix merge blocker template
  .github/ISSUE_TEMPLATE/merge-blocker.yml
Labels: approved, lgtm

#1330 OCPBUGS-3203: [metrics] Add check for endpoints subsets address
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug

#1321 OCPBUGS-3506: Upgrade Machine Nodes in place
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  test/e2e/create_test.go
  test/e2e/secrets_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1338 Bug 2072418: [docs] Add trunk port to the limitations
  README.md
Labels: approved, lgtm, bugzilla/valid-bug, bugzilla/severity-medium
