Repository openshift/windows-machine-config-operator, pull requests merged in 2023-12, with the labels that each got.

#1963 [release-4.14] Update version to 9.0.1
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1955 Stop using automatically generated service account token in e2e test suite
  test/e2e/metrics_test.go
Labels: approved, lgtm

#1907 [docs] Document storage limitations with CSI proxy
  README.md
Labels: approved, lgtm

#1917 OCPBUGS-22680: Ensure WICD service account token
  pkg/nodeconfig/nodeconfig.go
  pkg/secrets/secrets.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1926 [release-4.14] OCPBUGS-22984: Introduce upgrading label to block concurrent upgrades
  controllers/controllers.go
  hack/common.sh
  hack/e2e/resources/parallel-upgrade-checker-job.yaml
  hack/run-ci-e2e-test.sh
  pkg/metadata/metadata.go
  pkg/nodeconfig/nodeconfig.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1949 WINC-1181: Add pod CPU and Memory metrics
  bundle/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  config/windows-exporter/prometheusRule.yaml
  test/e2e/metrics_test.go
  test/e2e/storage_test.go
Labels: approved, lgtm, jira/valid-reference

#1978 [release-4.12] WINC-1177: Update version to 7.2.1
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference

#1982 [release-4.11] WINC-1176: Update version to 6.0.4
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference

#1965 WINC-1158: Prep for 10.16.0 release
  .ci-operator.yaml
  .gitmodules
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  bundle.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  hack/lint-gofmt.sh
Labels: approved, lgtm, jira/valid-reference

#1981 [release-4.13] WINC-1178: Update version to 8.1.2
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1979 OCPBUGS-21606,OCPBUGS-2887: Fix network config script
  pkg/nodeconfig/payload/payload.go
  pkg/nodeconfig/payload/payload_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1983 [bundle] remove scorecard from bundle.Dockerfile
  bundle.Dockerfile
Labels: approved, lgtm

#1931 [release-4.13] OCPBUGS-23016: Introduce upgrading label to block concurrent upgrades
  controllers/controllers.go
  hack/common.sh
  hack/e2e/resources/parallel-upgrade-checker-job.yaml
  hack/run-ci-e2e-test.sh
  pkg/metadata/metadata.go
  pkg/nodeconfig/nodeconfig.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
