Repository openshift/windows-machine-config-operator, pull requests merged in 2023-06, with the labels that each got.

#1634 [release-4.12] WINC-1037: Allows selecting Windows Server version for testing
  docs/HACKING.md
  hack/machineset.sh
  hack/run-ci-e2e-test.sh
  test/e2e/create_test.go
  test/e2e/main_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/validation_test.go
  test/e2e/windows/version.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#1637 [test] Use updated vSphere FSS ConfigMap values
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#1621 Reuse testContext across the test suite
  test/e2e/certificates_test.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/logs_test.go
  test/e2e/metrics_test.go
  test/e2e/network_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#1639 [vendor] Update goio to v1.3.3
  go.mod
  go.sum
  vendor/github.com/go-imports-organizer/goio/README.md
  vendor/github.com/go-imports-organizer/goio/main.go
  vendor/modules.txt
Labels: approved, lgtm

#1644 [release-4.12] OCPBUGS-14260: Check for minimum OCP version
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  pkg/cluster/config.go
  pkg/cluster/config_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1654 OCPBUGS-13780,OCPBUGS-14700: Use latest and version CM for cleanup
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/cleanup/cleanup_test.go
  test/e2e/delete_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1656 Ensure node becomes ready when configuring
  pkg/daemon/controller/controller.go
Labels: approved, lgtm

#1665 [release-4.13] Reuse testContext within each test suite
  test/e2e/certificates_test.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/logs_test.go
  test/e2e/metrics_test.go
  test/e2e/network_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#1664 [hack] Fix error when a PR links to multiple bugs
  hack/errata-check.sh
Labels: approved, lgtm

#1669 Remove unnecessary poll wait times
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
Labels: approved, lgtm
