Repository openshift/windows-machine-config-operator, pull requests merged in 2023-07, with the labels that each got.

#1671 OCPBUGS-15461: Fix WICD RBAC comparisons
  controllers/configmap_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1668 [wicd][controller] Fix Reconcile unit test
  pkg/daemon/controller/controller_test.go
Labels: approved, lgtm

#1676 Harden userdata tamper test
  test/e2e/secrets_test.go
Labels: approved, lgtm

#1681 Remove condition check in reconfigure test
  test/e2e/reconfigure_test.go
Labels: approved, lgtm

#1684 [release-4.11] OCPBUGS-15435: Install container feature silently
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1536 WINC-637: Set cluster-wide proxy environment variables on Windows instances
  cmd/operator/main.go
  controllers/controllers.go
  controllers/node_controller.go
  controllers/windowsmachine_controller.go
  pkg/cluster/config.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/metadata/metadata.go
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  pkg/servicescm/servicescm.go
  pkg/servicescm/servicescm_test.go
  pkg/windows/windows.go
  test/e2e/proxy_test.go
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/mksyscall.go
  vendor/golang.org/x/sys/windows/registry/syscall.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#1649 WINC-950: Test WMCO version upgrades
  Makefile
  hack/run-ci-e2e-test.sh
  test/e2e/create_test.go
  test/e2e/network_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1694 WINC-805: Document support for Windows Server 2022 on AWS
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-reference

#1679 [docs] Document Nutanix machineset sample
  README.md
  docs/machineset-nutanix.md
  docs/nutanix-prerequisites.md
  docs/wmco-prerequisites.md
Labels: approved, lgtm, docs-approved

#1695 WINC-1023: Remove WICD node deletion RBAC permission
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/wicd/windows-instance-config-daemon-cluster-role.yaml
Labels: approved, lgtm, jira/valid-reference

#1693 [release-4.13] Update version to 8.0.2
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1691 [hack] Remove version gen for csi-proxy
  hack/update_submodules.sh
Labels: approved, lgtm

#1690 [hack] Introduce vsphere CSI manifests
  hack/manifests/csi/vsphere/example-windows-daemonset-pvc-sc.yaml
Labels: approved, lgtm

#1697 WINC-945: [hack] Automate gitlab version updates
  hack/pre-release.sh
Labels: approved, lgtm, jira/valid-reference

#1704 [release-4.12] WINC-1028: Prep for 7.1.1 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference

#1689 [nodeconfig] Set node in NodeConfig constructor
  controllers/node_controller.go
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm
