Repository openshift/windows-machine-config-operator, pull requests merged in 2023-03, with the labels that each got.

#1427 WINC-736: Periodically correct service state
  pkg/daemon/controller/controller.go
  pkg/windows/service.go
  pkg/windows/windows.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1456 WINC-952: [master] Prep for 9.0.0 release
  Makefile
  bundle.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1461 [release 4.10][submodule] update 03/06
  Makefile
Labels: approved, lgtm

#1439 OCPBUGS-8055: [release-4.11] [build] Fix containerd version reporting
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  hack/update_submodules.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1426 WINC-535: Disable password auth for Windows Machine VMs
  pkg/secrets/secrets.go
Labels: approved, lgtm, jira/valid-reference

#1471 [release 4.9][submodule] update 03/09
  Makefile
Labels: approved, lgtm

#1464 [test] Capture stderr on oc adm node-logs failures
  test/e2e/logs_test.go
Labels: approved, lgtm

#1480 [hack] MachineSet script platform discovery fix
  hack/machineset.sh
Labels: approved, lgtm

#1479 OCPBUGS-10222: [metrics] Ignore case of cluster monitoring label
  pkg/metrics/metrics.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1498 [wmco] Remove netutil package
  pkg/instance/instance.go
  pkg/netutil/netutil.go
  pkg/netutil/netutil_test.go
  pkg/wiparser/wiparser.go
Labels: approved, lgtm

#1481 WINC-959: [docs] updates CONTRIBUTION.md
  CONTRIBUTION.md
Labels: approved, lgtm, jira/valid-reference

#1499 Use ClusterFirstWithHostNet DNS policy
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm

#1482 OCPBUGS-10572: Fix cleanup failure on WMCO upgrade
  pkg/windows/windows.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1492 [bundle] Fix metadata version annotation
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#1521 [test] Add framework for storage testing
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#1519 [wicd] Pass klog to controller-runtime
  pkg/daemon/controller/controller.go
Labels: approved, lgtm

#1514 [bundle] Fall back to using v4.13 OCP version label
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#1522 OCPBUGS-10437: Fix CNI conf
  pkg/nodeconfig/payload/payload.go
  pkg/nodeconfig/payload/payload_test.go
  test/e2e/network_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1506 [release-4.11] Assert that Windows pods use cluster DNS
  test/e2e/network_test.go
Labels: approved, lgtm

#1505 [release-4.10] Assert that Windows pods use cluster DNS
  test/e2e/network_test.go
Labels: approved, lgtm

#1525 [test] Add namespace for PVC creation
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm

#1531 [test] fix panic introduced by 0a5bad5
  test/e2e/logs_test.go
Labels: approved, lgtm
