Repository openshift/windows-machine-config-operator, pull requests merged in 2023-01, with the labels that each got.

#1365 WINC-956: Reduce direct use of the AWS API in e2e tests
  test/e2e/providers/aws/aws.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/doc.go
  vendor/github.com/aws/aws-sdk-go/service/iam/errors.go
  vendor/github.com/aws/aws-sdk-go/service/iam/service.go
  vendor/github.com/aws/aws-sdk-go/service/iam/waiters.go
  vendor/modules.txt
Labels: approved, lgtm

#1369 OCPBUGS-5065: Add namespace parameter and RBAC to WICD
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  cmd/daemon/bootstrap.go
  cmd/daemon/cleanup.go
  cmd/daemon/controller.go
  cmd/daemon/main.go
  cmd/operator/main.go
  config/rbac/role.yaml
  config/wicd/kustomization.yaml
  config/wicd/windows-instance-config-daemon-cluster-role-binding.yaml
  config/wicd/windows-instance-config-daemon-role-binding.yaml
  controllers/configmap_controller.go
  controllers/controllers.go
  hack/common.sh
  hack/run-ci-e2e-test.sh
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1367 WINC-677: [e2e] Modularize linux curler job creation
  test/e2e/metrics_test.go
  test/e2e/network_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#1378 OCPBUGS-5732: [wm_controller] Fix Machine node upgrades
  controllers/windowsmachine_controller.go
  pkg/nodeutil/nodeutil.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1375 [release-4.12] OCPBUGS-5749: Add namespace parameter and RBAC to WICD
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  cmd/daemon/bootstrap.go
  cmd/daemon/cleanup.go
  cmd/daemon/controller.go
  cmd/daemon/main.go
  cmd/operator/main.go
  config/rbac/role.yaml
  config/wicd/kustomization.yaml
  config/wicd/windows-instance-config-daemon-cluster-role-binding.yaml
  config/wicd/windows-instance-config-daemon-role-binding.yaml
  controllers/configmap_controller.go
  controllers/controllers.go
  hack/common.sh
  hack/run-ci-e2e-test.sh
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1371 WINC-923: bumps pause image from 3.6 to 3.9
  pkg/internal/containerd_conf.toml
Labels: approved, lgtm

#1386 OCPBUGS-5887: Check for error when deleting directories
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  pkg/windows/windows.go
  test/e2e/certificates_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug

#1332 WINC-733: Instance cleanup is done by WICD cleanup command
  cmd/daemon/cleanup.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/controller/controller.go
  pkg/daemon/fake/manager.go
  pkg/daemon/manager/manager.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
Labels: approved, lgtm

#1372 OCPBUGS-5354: Enable draining DaemonSet workloads
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  hack/run-ci-e2e-test.sh
  pkg/daemon/cleanup/cleanup.go
  pkg/nodeconfig/nodeconfig.go
  test/e2e/delete_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference
