Repository openshift/windows-machine-config-operator, pull requests merged in 2023-11, with the labels that each got.

#1920 WINC-1153: [release-4.13] Update version to 8.1.1
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1922 OCPBUGS-22824: Fix error handling for Approve()
  pkg/csr/csr.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1901 OCPBUGS-8996: Introduce `upgrading` label to block concurrent upgrades
  controllers/controllers.go
  hack/common.sh
  hack/e2e/resources/parallel-upgrade-checker-job.yaml
  hack/run-ci-e2e-test.sh
  pkg/metadata/metadata.go
  pkg/nodeconfig/nodeconfig.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1921 [doc] Support cluster-wide proxy in README
  README.md
Labels: approved, lgtm

#1883 [release-4.13] OCPBUGS-20259: Fix "WMCO does not wait for instance to reboot properly"
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1912 WINC-751: Upgrade sdk-operator to 1.32.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  cmd/operator/main.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  docs/HACKING.md
  hack/common.sh
  hack/pre-release.sh
Labels: approved, lgtm, jira/valid-reference
