Repository openshift/windows-machine-config-operator, pull requests merged in 2023-05, with the labels that each got.

#1596 Add goio to linter
  CONTRIBUTION.md
  Makefile
  cmd/daemon/service.go
  go.mod
  go.sum
  goio.yaml
  hack/lint-gofmt.sh
  pkg/condition/condition_test.go
  pkg/crypto/crypto_test.go
  pkg/daemon/fake/winsvc_test.go
  pkg/instance/instance.go
  pkg/metadata/metadata_test.go
  test/e2e/metrics_test.go
  tools.go
  vendor/github.com/go-imports-organizer/goio/.gitignore
  vendor/github.com/go-imports-organizer/goio/LICENSE
  vendor/github.com/go-imports-organizer/goio/Makefile
  vendor/github.com/go-imports-organizer/goio/README.md
  vendor/github.com/go-imports-organizer/goio/go.work
  vendor/github.com/go-imports-organizer/goio/goio.yaml
  vendor/github.com/go-imports-organizer/goio/main.go
  vendor/github.com/go-imports-organizer/goio/pkg/api/v1alpha1/types.go
  vendor/github.com/go-imports-organizer/goio/pkg/config/config.go
  vendor/github.com/go-imports-organizer/goio/pkg/excludes/excludes.go
  vendor/github.com/go-imports-organizer/goio/pkg/groups/groups.go
  vendor/github.com/go-imports-organizer/goio/pkg/imports/imports.go
  vendor/github.com/go-imports-organizer/goio/pkg/module/find.go
  vendor/github.com/go-imports-organizer/goio/pkg/sorter/sorter.go
  vendor/github.com/go-imports-organizer/goio/pkg/version/version.go
  vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
  vendor/golang.org/x/mod/modfile/print.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/golang.org/x/mod/modfile/work.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/module/pseudo.go
  vendor/modules.txt
Labels: approved, lgtm

#1599 [hack] infer OCP version from WMCO version
  hack/common.sh
Labels: approved, lgtm

#1595 WINC-635: Remove vSphere Machine deletion exception
  test/e2e/delete_test.go
Labels: approved, lgtm, jira/valid-reference

#1602 WINC-1036: Drop Azure support in WMCO 5.x and lower
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-reference

#1612 [release-4.10] WINC-1036: Drop Azure support in WMCO 5.x and lower
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-reference

#1586 WINC-1037: Allows selecting Windows Server version for testing
  docs/HACKING.md
  hack/machineset.sh
  hack/run-ci-e2e-test.sh
  test/e2e/create_test.go
  test/e2e/main_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/nutanix/nutanix.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/validation_test.go
  test/e2e/windows/version.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#1617 [build] Sync dockerfile comments with midstream
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
Labels: approved, lgtm

#1611 [release-4.11] WINC-1036: Drop Azure support in WMCO 5.x and lower
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-reference

#1566 WINC-860: [hack] Automate pre-release version updates
  hack/common.sh
  hack/pre-release.sh
  hack/update_submodules.sh
Labels: approved, lgtm, jira/valid-reference

#1598 WINC-999: WMCO manages new trusted CA ConfigMap
  cmd/operator/main.go
  controllers/configmap_controller.go
  hack/run-ci-e2e-test.sh
  pkg/cluster/config.go
  test/e2e/proxy_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#1620 Test suite enhancements around WMCO deployments
  hack/run-ci-e2e-test.sh
  test/e2e/main_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#1622 [release-4.12] OCPBUGS-13790: Address potential unitialized variables
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1628 [docs] Adds operator-sdk prequisite and version
  docs/HACKING.md
Labels: approved, lgtm

#1624 [release-4.13] WINC-1020: Update version to 8.0.1
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1626 OCPBUGS-13244: Install container feature silently
  pkg/windows/windows.go
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1618 [build] Update Dockerfile to use ubi9 images
  build/Dockerfile
  build/Dockerfile.base
Labels: approved, lgtm

#1627 WINC-860: [hack] Bugfixes for the post-release script
  hack/pre-release.sh
Labels: approved, lgtm, jira/valid-reference

#1615 [release-4.13] WINC-1037: Allows selecting Windows Server version for testing
  docs/HACKING.md
  hack/machineset.sh
  hack/run-ci-e2e-test.sh
  test/e2e/create_test.go
  test/e2e/main_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/validation_test.go
  test/e2e/windows/version.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#1632 [release-4.13] [build] Update Dockerfile to use ubi9 images
  build/Dockerfile
  build/Dockerfile.base
Labels: approved, lgtm
