Repository openshift/windows-machine-config-operator, pull requests merged in 2023-10, with the labels that each got.

#1823 OCPBUGS-19716: Enable proxy cert test to run in CI
  test/e2e/clusterinfo/openshift.go
  test/e2e/create_test.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1770 OCPBUGS-17217: Fix "WMCO does not wait for instance to reboot properly"
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1841 [hack] Add Azure File CSI Driver Manifests
  hack/manifests/csi/azure/01-example-driver-daemonset.yaml
  hack/manifests/csi/azure/02-example-namespace.yaml
  hack/manifests/csi/azure/03-example-sc.yaml
  hack/manifests/csi/azure/04-example-pvc.yaml
  hack/manifests/csi/azure/05-example-deployment.yaml
Labels: approved, lgtm

#1869 [release-4.12] [e2e] Wait for deleted machines in Azure
  test/e2e/create_test.go
Labels: approved, lgtm

#1870 [release-4.12] OCPBUGS-20139,OCPBUGS-20140: Use latest and version CM for cleanup
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/cleanup/cleanup_test.go
  test/e2e/delete_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1840 [release-4.13] WINC-1098: Block upgrades when migrating from in-tree to CSI
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/controllers.go
  controllers/controllers_test.go
  pkg/cluster/config.go
  pkg/metadata/metadata.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  vendor/k8s.io/kubelet/pkg/apis/stats/v1alpha1/types.go
  vendor/modules.txt
  version/version.go
Labels: approved, lgtm, jira/valid-reference

#1774 OCPBUGS-18554: Fix "error removing HNS network when cleaning up BYOH proxy nodes"
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1878 Adjust machineSet name for BYOH in machineset.sh
  hack/machineset.sh
Labels: approved, lgtm

#1889 [release-4.12] WINC-950: Test WMCO version upgrades
  Makefile
  hack/run-ci-e2e-test.sh
  test/e2e/create_test.go
  test/e2e/network_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1778 OCPBUGS-5002: Copy Azure setup files only on Azure
  pkg/csr/csr.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  pkg/windows/windows_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#1892 [hack] Change imagePullPolicy for olm.sh
  hack/common.sh
Labels: approved, lgtm

#1834 WINC-688: Support removing proxy certs from Windows nodes
  pkg/daemon/certs/certs.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/controller/controller.go
  test/e2e/delete_test.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, jira/valid-reference

#1891 Revert "[test] Enable upgrading from in-tree to CSI"
  hack/run-ci-e2e-test.sh
  test/e2e/logs_test.go
  test/e2e/main_test.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#1904 [build] Silence go compliance shim output
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
Labels: approved, lgtm

#1906 Add exclude to snyk configuration
  .snyk
Labels: approved, lgtm

#1800 OCPBUGS-19502: Enable proxy removal test
  hack/run-ci-e2e-test.sh
  test/e2e/delete_test.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1887 OCPBUGS-19039: [nodeconfig] Enable draining nodes with emptydir data
  pkg/nodeconfig/nodeconfig.go
  test/e2e/delete_test.go
  test/e2e/network_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
