Repository openshift/windows-machine-config-operator, pull requests merged in 2023-09, with the labels that each got.

#1707 WINC-1090: Support custom CA certificates for cluster-wide proxy
  cmd/daemon/controller.go
  pkg/daemon/certs/certs.go
  pkg/daemon/controller/controller.go
  pkg/windows/windows.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, jira/valid-reference

#1705 WINC-1043: Test upgrading to CSI storage, from in-tree drivers
  hack/run-ci-e2e-test.sh
  test/e2e/delete_test.go
  test/e2e/logs_test.go
  test/e2e/main_test.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm, jira/valid-reference

#1765 OCPBUGS-18294: WMCO is not reacting to new environment variables
  pkg/servicescm/servicescm.go
  pkg/servicescm/servicescm_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1773 WINC-1053: [build] Update to 4.15 image and prep for 10.15.0
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  bundle.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  hack/common.sh
Labels: approved, lgtm, jira/valid-reference

#1715 Adjust verbosity for csi-proxy service
  pkg/services/services.go
Labels: approved, lgtm

#1776 [release-4.14] [bundle] Bump to v4.14 OCP version label
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#1777 [test] SMB storage testing on Platform none
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/nutanix/nutanix.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/smb/smb.go
  test/e2e/storage_test.go
Labels: approved, lgtm

#1781 Allow possibility of nil Azure zone in CI
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm

#1772 OCPBUGS-15988: Restore routes on AWS Windows 2022 nodes
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/delete_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1798 [hack] Use full WMCO version in errata-check.sh
  hack/errata-check.sh
Labels: approved, lgtm

#1763 [test] Fix bad wait logic for NOOP DaemonSet
  test/e2e/delete_test.go
Labels: approved, lgtm

#1811 [release-4.12] Unblock aws-e2e-upgrade test
  hack/run-ci-e2e-test.sh
  test/e2e/delete_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
Labels: approved, lgtm

#1812 [release-4.13] Unblock aws-e2e-upgrade test
  hack/run-ci-e2e-test.sh
  test/e2e/delete_test.go
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
Labels: approved, lgtm

#1810 Prevent reconfigure test from leaving Machine nodes in a bad state
  hack/run-ci-e2e-test.sh
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
Labels: approved, lgtm

#1805 [release-4.13] OCPBUGS-19084: Restore routes on AWS Windows 2022 nodes
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/delete_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1806 Test Azure CSI storage
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm

#1822 [release-4.13] Test Azure CSI storage
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm

#1799 Skip BYOH removal test when no BYOH nodes
  test/e2e/delete_test.go
Labels: approved, lgtm

#1762 [daemon] Rename envVar function and variables
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/controller/controller.go
  pkg/daemon/envvar/envvar.go
Labels: approved, lgtm

#1821 [e2e] Wait for deleted machines in Azure
  test/e2e/create_test.go
Labels: approved, lgtm

#1794 [release-4.14] WINC-1098: Block upgrades when migrating from in-tree to CSI
  controllers/controllers.go
  controllers/controllers_test.go
  pkg/cluster/config.go
  pkg/metadata/metadata.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  version/version.go
Labels: approved, lgtm, jira/valid-reference

#1827 [release-4.13] WINC-1043: Test upgrading to CSI storage, from in-tree drivers
  hack/run-ci-e2e-test.sh
  test/e2e/delete_test.go
  test/e2e/logs_test.go
  test/e2e/main_test.go
  test/e2e/providers/azure/azure.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm, jira/valid-reference

#1813 Remove hard-coded default network for vSphere e2e test
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm
