Repository openshift/windows-machine-config-operator, pull requests merged in 2023-04, with the labels that each got.

#1537 OCPBUGS-11259: BYOH node upgrade failed with WICD RBAC permissions
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/wicd/windows-instance-config-daemon-cluster-role.yaml
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1541 [test] Move storage testing to its own test
  hack/run-ci-e2e-test.sh
  test/e2e/network_test.go
  test/e2e/storage_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#1535 [build] Update Dockerfiles to use rhel-9, openshift-4.13 base image
  .ci-operator.yaml
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
Labels: approved, lgtm

#1543 OCPBUGS-11306: [vpshere_ci] Disable IPv6 on Windows 2022
  docs/vsphere_ci/README.md
  docs/vsphere_ci/scripts/disable-ipv6.ps1
  docs/vsphere_ci/windows-server-2022.pkr.hcl
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1512 WINC-1001: [wmco] Use standard library errors package
  controllers/certificatesigningrequests_controller.go
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  go.mod
  pkg/certificates/certificates.go
  pkg/cluster/config.go
  pkg/condition/condition.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/csr/csr.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/config/config.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/fake/manager.go
  pkg/daemon/fake/winsvc.go
  pkg/daemon/fake/winsvc_test.go
  pkg/daemon/manager/manager.go
  pkg/daemon/powershell/powershell.go
  pkg/daemon/winsvc/winsvc.go
  pkg/ignition/ignition.go
  pkg/instance/instance.go
  pkg/metadata/metadata.go
  pkg/metrics/metrics.go
  pkg/nodeconfig/init.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/payload/payload.go
  pkg/secrets/secrets.go
  pkg/services/services.go
  pkg/servicescm/servicescm.go
  pkg/signer/signer.go
  pkg/windows/connectivity.go
  pkg/windows/service.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
  test/e2e/certificates_test.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/logs_test.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1520 [release-4.12] OCPBUGS-10784: Correct CSI feature gates
  hack/run-ci-e2e-test.sh
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/nodeconfig_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/storage_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1552 OCPBUGS-11306: [test] Use IPv6 disabled template for Windows 2022
  hack/machineset.sh
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1546 [release-4.13] WINC-1001: [wmco] Use standard library errors package
  controllers/certificatesigningrequests_controller.go
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  go.mod
  pkg/certificates/certificates.go
  pkg/cluster/config.go
  pkg/condition/condition.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/csr/csr.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/config/config.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/fake/manager.go
  pkg/daemon/fake/winsvc.go
  pkg/daemon/fake/winsvc_test.go
  pkg/daemon/manager/manager.go
  pkg/daemon/powershell/powershell.go
  pkg/daemon/winsvc/winsvc.go
  pkg/ignition/ignition.go
  pkg/instance/instance.go
  pkg/metadata/metadata.go
  pkg/metrics/metrics.go
  pkg/netutil/netutil.go
  pkg/nodeconfig/init.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/payload/payload.go
  pkg/secrets/secrets.go
  pkg/services/services.go
  pkg/servicescm/servicescm.go
  pkg/signer/signer.go
  pkg/windows/connectivity.go
  pkg/windows/service.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
  test/e2e/certificates_test.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/logs_test.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1513 WINC-959: [docs] updates HACKING.md
  docs/HACKING.md
  docs/custom-workload.md
  docs/setup-hybrid-OVNKubernetes-cluster.md
Labels: approved, lgtm, jira/valid-reference

#1565 Revert "[release-4.13] WINC-1001: [wmco] Use standard library errors package"
  controllers/certificatesigningrequests_controller.go
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  go.mod
  pkg/certificates/certificates.go
  pkg/cluster/config.go
  pkg/condition/condition.go
  pkg/crypto/crypto.go
  pkg/crypto/crypto_test.go
  pkg/csr/csr.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/config/config.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/fake/manager.go
  pkg/daemon/fake/winsvc.go
  pkg/daemon/fake/winsvc_test.go
  pkg/daemon/manager/manager.go
  pkg/daemon/powershell/powershell.go
  pkg/daemon/winsvc/winsvc.go
  pkg/ignition/ignition.go
  pkg/instance/instance.go
  pkg/metadata/metadata.go
  pkg/metrics/metrics.go
  pkg/netutil/netutil.go
  pkg/nodeconfig/init.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/payload/payload.go
  pkg/secrets/secrets.go
  pkg/services/services.go
  pkg/servicescm/servicescm.go
  pkg/signer/signer.go
  pkg/windows/connectivity.go
  pkg/windows/service.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
  test/e2e/certificates_test.go
  test/e2e/create_test.go
  test/e2e/delete_test.go
  test/e2e/logs_test.go
  test/e2e/main_test.go
  test/e2e/metrics_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/gcp/gcp.go
  test/e2e/providers/none/none.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1554 [release-4.10] OCPBUGS-11898: Disable IPv6 on Windows 2022
  docs/vsphere_ci/README.md
  docs/vsphere_ci/scripts/disable-ipv6.ps1
  docs/vsphere_ci/windows-server-2022.pkr.hcl
  hack/machineset.sh
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1584 WINC-1040: Use Version annotation for service removal in WICD cleanup
  pkg/daemon/cleanup/cleanup.go
Labels: approved, lgtm, jira/valid-reference

#1555 WINC-561: Set kubelet priority flag
  pkg/services/services.go
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1398 WINC-1035: Support Nutanix platform
  controllers/configmap_controller.go
  controllers/windowsmachine_controller.go
  test/e2e/create_test.go
  test/e2e/network_test.go
  test/e2e/providers/cloudprovider.go
  test/e2e/providers/nutanix/nutanix.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1573 WINC-1033: Use latest WICD binary during upgrades
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-reference
