Repository openshift/windows-machine-config-operator, pull requests merged in 2023-08, with the labels that each got.

#1710 WMCO removes reboot annotation instead of WICD
  pkg/daemon/controller/controller.go
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm

#1714 Add csi-proxy logs collection in e2e test suite
  test/e2e/logs_test.go
Labels: approved, lgtm

#1711 WINC-633: Copy additional CA bundle to Windows instances
  controllers/configmap_controller.go
  pkg/certificates/certificates.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, jira/valid-reference

#1713 [hack] Improve vSphere CSI Manifests
  hack/manifests/csi/vsphere/01-example-driver-daemonset.yaml
  hack/manifests/csi/vsphere/02-example-namespace.yaml
  hack/manifests/csi/vsphere/03-example-sc.yaml
  hack/manifests/csi/vsphere/04-example-pvc.yaml
  hack/manifests/csi/vsphere/05-example-deployment.yaml
Labels: approved, lgtm

#1717 [release-4.11] WINC-1056: Update version to 6.0.2
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference

#1719 [aws] Avoid Windows Server 2019 `Containers` image
  hack/machineset.sh
  test/e2e/providers/aws/aws.go
Labels: approved, lgtm

#1724 [release-4.11] [aws] Avoid Windows Server 2019 `Containers` image
  hack/machineset.sh
  test/e2e/providers/aws/aws.go
Labels: approved, lgtm

#1716 [release-4.10] WINC-1055: Prep for 5.1.2 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference

#1730 WINC-1092: [release-4.10][docs] Drop AWS support in WMCO 5.x and lower
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-reference

#1729 WINC-1092: [docs] Drop AWS support in WMCO 5.x and lower
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-reference

#1647 [release-4.13] [vendor] Update goio to v1.3.3
  go.mod
  go.sum
  vendor/github.com/go-imports-organizer/goio/README.md
  vendor/github.com/go-imports-organizer/goio/main.go
  vendor/modules.txt
Labels: approved, lgtm

#1735 WINC-1092: [release-4.11][docs] Drop AWS support in WMCO 5.x and lower
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-reference

#1725 OCPBUGS-17528: Get kubeletCA from controller configuration
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  pkg/ignition/ignition.go
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#1737 [release-4.12] OCPBUGS-17639: Allow WMCO to run on nightly clusters
  pkg/cluster/config.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1738 [release-4.13] Ensure node becomes ready when configuring
  pkg/daemon/controller/controller.go
Labels: approved, lgtm

#1708 WINC-861: [hack] Automate x-stream gitlab branch updates
  hack/pre-release.sh
Labels: approved, lgtm, jira/valid-reference

#1743 Use ParseCompatibleVersion when parsing ignition
  pkg/ignition/ignition.go
Labels: approved, lgtm

#1747 [servicescm] Use generics for Services and Files
  pkg/servicescm/servicescm.go
Labels: approved, lgtm

#1706 WINC-998: Clear proxy variables from Windows nodes
  pkg/cluster/config.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/cleanup/cleanup_test.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/daemon/envvar/envvar.go
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  pkg/servicescm/servicescm.go
  pkg/servicescm/servicescm_test.go
  test/e2e/delete_test.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, jira/valid-reference

#1648 [release-4.12] Add goio to linter
  CONTRIBUTION.md
  Makefile
  cmd/daemon/service.go
  go.mod
  go.sum
  goio.yaml
  hack/lint-gofmt.sh
  pkg/cluster/config.go
  pkg/condition/condition_test.go
  pkg/crypto/crypto_test.go
  pkg/daemon/fake/winsvc_test.go
  pkg/instance/instance.go
  pkg/metadata/metadata_test.go
  test/e2e/metrics_test.go
  tools.go
  vendor/github.com/go-imports-organizer/goio/.gitignore
  vendor/github.com/go-imports-organizer/goio/LICENSE
  vendor/github.com/go-imports-organizer/goio/Makefile
  vendor/github.com/go-imports-organizer/goio/README.md
  vendor/github.com/go-imports-organizer/goio/go.work
  vendor/github.com/go-imports-organizer/goio/goio.yaml
  vendor/github.com/go-imports-organizer/goio/main.go
  vendor/github.com/go-imports-organizer/goio/pkg/api/v1alpha1/types.go
  vendor/github.com/go-imports-organizer/goio/pkg/config/config.go
  vendor/github.com/go-imports-organizer/goio/pkg/excludes/excludes.go
  vendor/github.com/go-imports-organizer/goio/pkg/groups/groups.go
  vendor/github.com/go-imports-organizer/goio/pkg/imports/imports.go
  vendor/github.com/go-imports-organizer/goio/pkg/module/find.go
  vendor/github.com/go-imports-organizer/goio/pkg/sorter/sorter.go
  vendor/github.com/go-imports-organizer/goio/pkg/version/version.go
  vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
  vendor/golang.org/x/mod/modfile/print.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/golang.org/x/mod/modfile/work.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/module/pseudo.go
  vendor/modules.txt
Labels: approved, lgtm

#1752 [release-4.11] WINC-1109: Update version to 6.0.3
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference

#1751 [release-4.12] WINC-1108: Update version to 7.2.0
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm, jira/valid-reference

#1759 [release-4.12] Revert "[nodeconfig] Ensure cached WICD creds are set"
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm

#1753 WINC-1107: [release-4.13] Update version to 8.1.0
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1733 WINC-1043: Upgrade test improvements
  hack/run-ci-e2e-test.sh
  test/e2e/upgrade_test.go
Labels: approved, lgtm, jira/valid-reference
