Repository openshift/windows-machine-config-operator, pull requests merged in 2023-02, with the labels that each got.

#1396 WINC-930: Prep for 7.0.1 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1390 Remove gcloud dependency in hack/machineset.sh
  hack/machineset.sh
Labels: approved, lgtm

#1399 OCPBUGS-6611: Wait until processes exit when stopping services
  pkg/daemon/manager/manager.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1400 Use error code to determine svc existence
  pkg/daemon/manager/manager.go
Labels: approved, lgtm

#1397 WINC-741: WICD takes more responsibility of Node configuration
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/wicd/windows-instance-config-daemon-cluster-role.yaml
  controllers/controllers.go
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  pkg/cluster/config.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/metadata/metadata.go
  pkg/nodeconfig/nodeconfig.go
  pkg/secrets/secrets.go
  pkg/servicescm/servicescm.go
  pkg/windows/windows.go
  test/e2e/delete_test.go
  test/e2e/providers/aws/aws.go
  test/e2e/providers/azure/azure.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/secrets_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1401 OCPBUGS-6635: [build] Fix k8s version reporting
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  hack/update_submodules.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1405 OCPBUGS-7287: Fix Kublet logs are not written to kubelet.log
  pkg/services/services.go
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#1389 WINC-920: Use Windows Server 2019 for Azure e2e tests
  test/e2e/network_test.go
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm

#1412 WINC-981: [release-4.12] Prep for 7.1.0 release
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#1373 WIP: Please ignore
  Makefile
Labels: do-not-merge/work-in-progress

#1407 [release-4.12] OCPBUGS-7336: [build] Fix k8s version reporting
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  hack/update_submodules.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1422 WINC-838: Add OS field to pod spec in Windows Server deployment
  README.md
  test/e2e/delete_test.go
  test/e2e/network_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference

#1423 OCPBUGS-5378: [build] Fix containerd version reporting
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  hack/update_submodules.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1404 [test] Improve error logging for DaemonSet
  test/e2e/delete_test.go
Labels: approved, lgtm

#1425 Revert "[release-4.12] WINC-949: Rename powershellVariablesInCommand"
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/services/services.go
  pkg/servicescm/servicescm.go
  pkg/servicescm/servicescm_test.go
Labels: approved, lgtm, jira/valid-reference

#1424 [release-4.12] OCPBUGS-7843: [build] Fix containerd version reporting
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  hack/update_submodules.sh
Labels: approved, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#1421 WINC-983: [e2e] Ensure required log files are non-empty
  test/e2e/logs_test.go
Labels: approved, lgtm, jira/valid-reference
