Repository openshift/windows-machine-config-operator, pull requests merged in 2024-01, with the labels that each got.

#1980 Add support for Nutanix in machineset.sh
  hack/machineset.sh
Labels: approved, lgtm

#1999 [controllers] Introduce err check when merging CA configmaps
  controllers/controllers.go
Labels: approved, lgtm

#2002 [release-4.12] Revert extra private key secret creation
  test/e2e/create_test.go
Labels: approved, lgtm

#1998 OCPBUGS-24264: [cluster] Keep comma as delimiter in noProxy list
  pkg/cluster/config.go
  pkg/daemon/controller/controller_test.go
  test/e2e/create_test.go
  test/e2e/proxy_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2006 OCPBUGS-26761: Use DSR load balancing in kube-proxy
  cmd/operator/main.go
  docs/byoh-instance-pre-requisites.md
  docs/vsphere-golden-image.md
  docs/vsphere_ci/scripts/install-firewall-rules.ps1
  pkg/nodeconfig/payload/payload.go
  pkg/nodeconfig/payload/payload_test.go
  pkg/secrets/secrets.go
  pkg/services/services.go
  pkg/windows/windows.go
  test/e2e/create_test.go
  test/e2e/network_test.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2022 [hack] Add JIRA status to errata script
  hack/errata-check.sh
Labels: approved, lgtm

#2038 [hack] Add relative PR merge times to errata script
  hack/errata-check.sh
Labels: approved, lgtm

#2043 [release-4.15] Revert "Change sourceVIP used for kube-proxy"
  cmd/operator/main.go
  pkg/nodeconfig/payload/payload.go
  pkg/nodeconfig/payload/payload_test.go
  pkg/windows/windows.go
Labels: approved, lgtm

#2028 Revert "Change sourceVIP used for kube-proxy"
  cmd/operator/main.go
  pkg/nodeconfig/payload/payload.go
  pkg/nodeconfig/payload/payload_test.go
  pkg/windows/windows.go
Labels: approved, lgtm

#2039 [build] Set go toolchain to local
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
Labels: approved, lgtm

#2051 OCPBUGS-28575: Fix issue with PS type mismatch
  pkg/nodeconfig/payload/payload.go
  pkg/nodeconfig/payload/payload_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
