Repository openshift/windows-machine-config-operator, pull requests merged in 2024-10, with the labels that each got.

#2422 WINC-1337: Use upstreamed dependency code
  pkg/daemon/fake/manager.go
  pkg/daemon/fake/winsvc.go
  pkg/daemon/manager/manager.go
  pkg/daemon/winsvc/winsvc.go
Labels: approved, lgtm, jira/valid-reference

#2435 [release-4.17] Update version to 10.17.1
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2436 [release-4.12] Update version to 7.2.3
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2452 WINC-1329: [bundle.Dockerfile] Update supported version to 4.18
  bundle.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#2448 OCPBUGS-42827: [release-4.17] Adjust k8s version for kube 1.30
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  pkg/cluster/config.go
  pkg/cluster/config_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-reference

#2471 Hardcode Azure SKU version for 2019 nodes
  hack/machineset.sh
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm

#2433 OCPBUGS-35285: Remove HNS networks before rebooting in AWS
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/reconfigure_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2498 [release-4.17] Update konflux for 4.17
  .tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm
