Repository openshift/windows-machine-config-operator, pull requests merged in 2024-08, with the labels that each got.

#2294 [e2e] Increase retry interval for mirror test
  test/e2e/mirror_test.go
Labels: approved, lgtm

#2315 [release-4.16] Konflux 0.1 -> 0.2 migration
  .tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml
  .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-16-push.yaml
Labels: approved, lgtm

#2316 [release-4.15] Konflux 0.1 -> 0.2 migration
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
Labels: approved, lgtm

#2317 [release-4.14] Konflux 0.1 -> 0.2 migration
  .tekton/windows-machine-config-operator-bundle-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-push.yaml
  .tekton/windows-machine-config-operator-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-14-push.yaml
Labels: approved, lgtm

#2319 [release-4.12] Konflux 0.1 -> 0.2 migration
  .tekton/windows-machine-config-operator-bundle-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-push.yaml
  .tekton/windows-machine-config-operator-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-12-push.yaml
Labels: approved, lgtm

#2318 [release-4.13] Konflux 0.1 -> 0.2 migration
  .tekton/windows-machine-config-operator-bundle-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-13-push.yaml
  .tekton/windows-machine-config-operator-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-13-push.yaml
Labels: approved, lgtm

#2295 WINC-1314: Use 4.17 Red Hat operator index
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm, jira/valid-reference

#2293 [test] Job log collection as a single action
  test/e2e/network_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm

#2296 WINC-1149: Use userdata task to persistent instance metadata routes in AWS
  README.md
  pkg/nodeconfig/nodeconfig.go
  pkg/secrets/secrets.go
  pkg/windows/windows.go
  test/e2e/create_test.go
Labels: approved, lgtm, jira/valid-reference

#2340 [release-4.16] Update version to 10.16.1
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2286 WINC-1320: Use registry.k8s.io instead of old k8s.gcr.io
  hack/manifests/csi/vsphere/01-example-driver-daemonset.yaml
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/smb/smb.go
Labels: approved, lgtm, jira/valid-reference

#2271 Update and clarify CI test script and usage instructions
  Makefile
  docs/HACKING.md
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#2360 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/windows-machine-config-operator-bundle-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-push.yaml
  .tekton/windows-machine-config-operator-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-12-push.yaml
Labels: approved, lgtm, ok-to-test

#2361 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/windows-machine-config-operator-bundle-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-13-push.yaml
  .tekton/windows-machine-config-operator-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-13-push.yaml
Labels: approved, lgtm, ok-to-test

#2362 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/windows-machine-config-operator-bundle-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-push.yaml
  .tekton/windows-machine-config-operator-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-14-push.yaml
Labels: approved, lgtm, ok-to-test

#2363 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
Labels: approved, lgtm, ok-to-test

#2291 OCPBUGS-36305: Document graceful Node reboot and add workaround for issue in AWS
  README.md
  docs/TROUBLESHOOTING.md
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2364 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml
  .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-16-push.yaml
Labels: approved, lgtm, ok-to-test

#2156 WINC-588: Expose metrics over https
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  bundle/manifests/windows-exporter_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/manifests/windows-exporter_v1_service.yaml
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  cmd/operator/main.go
  config/rbac/role.yaml
  config/windows-exporter/windows-exporter-service-monitor.yaml
  config/windows-exporter/windows-exporter-service.yaml
  controllers/secret_controller.go
  go.mod
  pkg/internal/windows-exporter-webconfig.yaml
  pkg/metrics/metrics.go
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/payload/payload.go
  pkg/secrets/secrets.go
  pkg/services/services.go
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-reference

#2378 WMCO update link to cost management in Other Limitations
  README.md
Labels: approved, lgtm

#2376 [release-4.15] OCPBUGS-38485: Always use created WICD SA token
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2380 [bundle] Fix 'make bundle'
  bundle/manifests/windows-exporter_v1_service.yaml
  config/windows-exporter/kustomization.yaml
  pkg/metrics/metrics.go
Labels: approved, lgtm

#2389 [build] Fix Dockerfile WORKDIR
  build/Dockerfile
Labels: approved, lgtm

#2405 [release-4.16] WINC-1325: Update version to 10.16.2
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2407 [release-4.15] WINC-1297: Update version to 10.15.4
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference
