Repository openshift/windows-machine-config-operator, pull requests merged in 2024-06, with the labels that each got.

#2191 WINC-1292: Add konflux configuration files to enable master pipeline
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
  build/Dockerfile.konflux
Labels: approved, lgtm, jira/valid-reference

#2193 [build] Fix konflux config
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
Labels: approved, lgtm

#2187 WINC-1290: [release-4.13] Set buildvcs false
  Makefile
Labels: approved, lgtm, jira/valid-reference

#2163 WINC-1222: WMCO applies image mirroring settings to Windows instances
  controllers/registry_controller.go
  hack/run-ci-e2e-test.sh
  pkg/nodeconfig/nodeconfig.go
  pkg/registries/registries.go
  pkg/registries/registries_test.go
  pkg/windows/connectivity.go
  pkg/windows/windows.go
  test/e2e/delete_test.go
  test/e2e/mirror_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#2201 WINC-1292: Set up konflux bundle builds
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#2204 Don't trigger unecessary konflux builds
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
Labels: approved, lgtm

#2205 [release-4.16] WINC-1309: Add konflux configuration files
  .tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml
  .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-16-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#2206 [release-4.16] Correct konflux image push registry
  .tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml
  .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-16-push.yaml
Labels: approved, lgtm

#2208 [release-4.15] WINC-1309: Add konflux build files
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm, jira/valid-reference

#2202 [release-4.13] OCPBUGS-34669: changes needed for validating webhook
  pkg/services/services.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2200 WINC-1294: Support token-based auth for mirror registries
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  controllers/registry_controller.go
  go.mod
  go.sum
  pkg/registries/registries.go
  pkg/registries/registries_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/doc.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/keyring.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/client_adapter.go
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#2214 [build] Use 4.16 index
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#2213 [release-4.16] WINC-1294: Support token-based auth for mirror registries
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  controllers/registry_controller.go
  go.mod
  go.sum
  pkg/registries/registries.go
  pkg/registries/registries_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/LICENSE
  vendor/k8s.io/apiserver/pkg/features/OWNERS
  vendor/k8s.io/apiserver/pkg/features/kube_features.go
  vendor/k8s.io/apiserver/pkg/util/feature/feature_gate.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/credentialprovider/OWNERS
  vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/doc.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/keyring.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/plugins.go
  vendor/k8s.io/kubernetes/pkg/credentialprovider/provider.go
  vendor/k8s.io/kubernetes/pkg/features/OWNERS
  vendor/k8s.io/kubernetes/pkg/features/kube_features.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-reference

#2212 WINC-1291: Use all existing CAs for TLS auth when pulling images
  controllers/configmap_controller.go
  controllers/controllerconfig_controller.go
  pkg/nodeconfig/nodeconfig.go
  pkg/registries/registries.go
  pkg/registries/registries_test.go
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-reference

#2211 WINC-1310: Remove certain tests in old upgrade suite
  Makefile
  hack/run-ci-e2e-test.sh
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#2216 WINC-1291: Document disconnected
  README.md
Labels: approved, lgtm, jira/valid-reference

#2228 [release-4.14] OCPBUGS-35572: Use kubelet-ca.crt from ControllerConfig
  cmd/operator/main.go
  controllers/configmap_controller.go
  controllers/controllerconfig_controller.go
  controllers/controllers.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2217 [release-4.13] OCPBUGS-34669: changes needed for validating webhook
  controllers/configmap_controller.go
  pkg/services/services.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2223 WINC-1311: [test] Return logs early on success
  test/e2e/metrics_test.go
  test/e2e/network_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-reference
