Repository openshift/windows-machine-config-operator, pull requests merged in 2024-07, with the labels that each got.

#2235 [release-4.13] Add konflux build files
  .tekton/windows-machine-config-operator-bundle-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-13-push.yaml
  .tekton/windows-machine-config-operator-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-13-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2236 [release-4.12] Add konflux build files
  .tekton/windows-machine-config-operator-bundle-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-push.yaml
  .tekton/windows-machine-config-operator-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-12-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2234 [release-4.14] Add konflux build files
  .tekton/windows-machine-config-operator-bundle-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-push.yaml
  .tekton/windows-machine-config-operator-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-14-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2232 OCPBUGS-35936: Update WICD args to include CA bundle path
  hack/run-ci-e2e-test.sh
  pkg/registries/registries.go
  pkg/registries/registries_test.go
  pkg/windows/windows.go
  test/e2e/create_test.go
  test/e2e/main_test.go
  test/e2e/mirror_test.go
  test/e2e/network_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2244 Align machineset.sh with 4.17 updates for securityGroups and subnet in AWS
  hack/machineset.sh
Labels: approved, lgtm

#2249 [release-4.15] WINC-1310: Remove certain tests in old upgrade suite
  Makefile
  hack/run-ci-e2e-test.sh
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#2248 OCPBUGS-36395: [config] Increase controller manager resource limits
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2252 [release-4.12] WINC-1310: Remove certain tests in old upgrade suite
  Makefile
  hack/run-ci-e2e-test.sh
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#2251 [release-4.13] WINC-1310: Remove certain tests in old upgrade suite
  Makefile
  hack/run-ci-e2e-test.sh
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#2256 OCPBUGS-36643: Handle reverse lookup error correctly
  pkg/csr/csr.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2221 [docs] Update details for upgrade process
  README.md
Labels: approved, lgtm

#2219 [docs] Remove hard-coded links to older OCP version
  README.md
Labels: approved, lgtm

#2250 [release-4.14] WINC-1310: Remove certain tests in old upgrade suite
  Makefile
  hack/run-ci-e2e-test.sh
  test/e2e/reconfigure_test.go
  test/e2e/secrets_test.go
  test/e2e/upgrade_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/valid-reference

#2279 OCPBUGS-29253, WINC-1172: Always use created WICD SA token
  pkg/nodeconfig/nodeconfig.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2027 WINC-1199: Fix VM creation automation in new vCenter
  docs/vsphere_ci/README.md
  docs/vsphere_ci/vcenter_copy_template/README.md
  docs/vsphere_ci/vcenter_copy_template/getem.sh
  docs/vsphere_ci/vcenter_copy_template/options.json
  docs/vsphere_ci/vcenter_copy_template/putem.sh
  docs/vsphere_ci/vcenter_copy_template/sourcedevqe
  docs/vsphere_ci/vcenter_copy_template/sourceibm-ci
  docs/vsphere_ci/vcenter_copy_template/sourcevcs8e
  docs/vsphere_ci/windows-server-2022.pkr.hcl
Labels: approved, lgtm, jira/valid-reference

#2272 OCPBUGS-30995: Bypass ExecutionPolicy running commands
  pkg/daemon/powershell/powershell.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
