Repository openshift/windows-machine-config-operator, pull requests merged in 2024-05, with the labels that each got.

#2153 [e2e] bump generated key size
  test/e2e/proxy_test.go
  test/e2e/secrets_test.go
Labels: approved, lgtm

#2140 WINC-1221: WMCO generates hosts.toml file content
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  cmd/operator/main.go
  config/rbac/role.yaml
  controllers/registry_controller.go
  pkg/registries/registries.go
  pkg/registries/registries_test.go
Labels: approved, lgtm, jira/valid-reference

#2155 WINC-1150: Reduce unecessary log messages
  pkg/daemon/controller/controller.go
  pkg/metrics/metrics.go
Labels: approved, lgtm, jira/valid-reference

#2166 Improve logging for malformed RBAC reconciliation and use context for WICD rbac operations
  cmd/operator/main.go
  controllers/configmap_controller.go
Labels: approved, lgtm

#2167 OCPBUGS-22237: Use kubelet-ca.crt from ControllerConfig when certs rotate
  cmd/operator/main.go
  controllers/configmap_controller.go
  controllers/controllerconfig_controller.go
  controllers/controllers.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2177 [release-4.14] WINC-1275: Update version to 9.0.3
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2168 [doc] Adjust private registry support statement
  README.md
Labels: approved, lgtm

#2174 [docs] bump vmtools image and auth keys for vSphere CI
  docs/vsphere_ci/README.md
  docs/vsphere_ci/scripts/authorized_keys
  docs/vsphere_ci/windows-server-2022.pkr.hcl
Labels: approved, lgtm

#2186 OCPBUGS-33319: use FQDN for hostname in vSphere
  pkg/csr/csr.go
  pkg/services/services.go
  pkg/services/services_test.go
  pkg/windows/windows.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference
