Repository openshift/windows-machine-config-operator, pull requests merged in 2024-04, with the labels that each got.

#2117 OCPBUGS-31626: Stop checking CloudControllerOwner
  controllers/configmap_controller.go
  pkg/cluster/config.go
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2118 [release-4.13] Update version to 8.1.3
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2122 [release-4.15] submodule update 04/03
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#2121 [release-4.15] OCPBUGS-31704: Stop checking CloudControllerOwner
  controllers/configmap_controller.go
  pkg/cluster/config.go
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#2115 OCPBUGS-20255: Let caller of Run handle error logging
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2116 Collect node logs on e2e failure
  test/e2e/create_test.go
  test/e2e/upgrade_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm

#2123 [hack] Allow authenticating with JIRA
  hack/errata-check.sh
Labels: approved, lgtm

#2132 [release-4.12] Update version to 7.2.2
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2133 [test] Increase upgrade test timeout
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm

#2114 WINC-1220: Set config_path for containerd registry settings
  pkg/internal/containerd_conf.toml
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-reference

#2135 [hack] add helper script for cluster-wide proxy
  hack/setup-cluster-wide-proxy.sh
Labels: approved, lgtm

#2141 [doc] Remove stale references to networking doc
  docs/TROUBLESHOOTING.md
  docs/vsphere-golden-image.md
  docs/vsphere-prerequisites.md
  docs/wmco-prerequisites.md
Labels: approved, lgtm

#2094 WINC-1184: Add support for 10.y.z version parsing in hack scripts
  hack/common.sh
Labels: approved, lgtm, jira/valid-reference

#2148 WINC-1180: Use record created for container_network metrics
  bundle/manifests/windows-prometheus-k8s-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  config/windows-exporter/prometheusRule.yaml
  test/e2e/metrics_test.go
Labels: approved, lgtm, jira/valid-reference
