Repository openshift/windows-machine-config-operator, pull requests merged in 2024-11, with the labels that each got.

#2486 OCPBUGS-18898: Highlight UPI support for platform:none and update pre-req docs
  docs/wmco-prerequisites.md
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#2502 Revert "OCPBUGS-35285: Remove HNS networks before rebooting in AWS"
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/windows.go
  test/e2e/reconfigure_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2522 [release-4.13] Update konflux
  .tekton/windows-machine-config-operator-bundle-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-13-push.yaml
  .tekton/windows-machine-config-operator-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-13-push.yaml
Labels: approved, lgtm

#2520 [release-4.15] Update konflux
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
Labels: approved, lgtm

#2523 [release-4.12] Update konflux
  .tekton/windows-machine-config-operator-bundle-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-push.yaml
  .tekton/windows-machine-config-operator-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-12-push.yaml
Labels: approved, lgtm

#2521 [release-4.14] Update konflux
  .tekton/windows-machine-config-operator-bundle-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-push.yaml
  .tekton/windows-machine-config-operator-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-14-push.yaml
Labels: approved, lgtm

#2524 [release-4.17] Update konflux
  .tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
Labels: approved, lgtm

#2485 WINC-545: Improve handling of metrics configuration
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  cmd/operator/main.go
  config/rbac/role.yaml
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/metric_controller.go
  controllers/windowsmachine_controller.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  test/e2e/metrics_test.go
Labels: approved, lgtm, jira/valid-reference

#2533 WINC-1352: Build CNI plugins with CGO_ENABLED
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.konflux
Labels: approved, lgtm, jira/valid-reference

#2539 Add generated MachineSet.yaml to gitignore
  .gitignore
Labels: approved, lgtm

#2546 [release-4.17] Prevent some submodule auto-updates
  renovate.json
Labels: approved, lgtm
