Repository openshift/windows-machine-config-operator, pull requests merged in 2024-09, with the labels that each got.

#2403 [release-4.12] Disable buildvcs for ovn-kubernetes build
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.konflux
Labels: approved, lgtm

#2412 [release-4.14] WINC-1300: Update version to 9.0.4
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2411 [release-4.13] WINC-1280: Update version to 8.1.4
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2431 WINC-1326: Use new repo for vSphere CSI driver image
  hack/manifests/csi/vsphere/01-example-driver-daemonset.yaml
  test/e2e/providers/vsphere/vsphere.go
Labels: approved, lgtm, jira/valid-reference

#2220 WINC-1315: Document steps for EUS-to-EUS upgrade
  README.md
Labels: approved, lgtm, jira/valid-reference

#2379 WINC-710: replaces kube-proxy flags with config file
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/nodeconfig/payload/payload.go
  pkg/nodeconfig/payload/payload_test.go
  pkg/services/services.go
  pkg/servicescm/servicescm.go
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-reference

#2408 OCPBUGS-16711, WINC-853: WICD best effort cleans up removes all managed services
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/cleanup/cleanup_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference
