Repository openshift/windows-machine-config-operator, pull requests merged in 2024-02, with the labels that each got.

#2041 [release-4.14] OCPBUGS-28226: Use DSR load balancing in kube-proxy
  docs/byoh-instance-pre-requisites.md
  docs/vsphere-golden-image.md
  docs/vsphere_ci/scripts/install-firewall-rules.ps1
  pkg/secrets/secrets.go
  pkg/services/services.go
  test/e2e/create_test.go
  test/e2e/network_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2040 WINC-511: Use RuntimeClass in e2e tests
  docs/custom-workload.md
  docs/windows-workloads.md
  test/e2e/network_test.go
  test/e2e/windows/version.go
Labels: approved, lgtm, jira/valid-reference

#2042 [release-4.13] OCPBUGS-28253: Use DSR load balancing in kube-proxy
  docs/byoh-instance-pre-requisites.md
  docs/vsphere-golden-image.md
  docs/vsphere_ci/scripts/install-firewall-rules.ps1
  pkg/secrets/secrets.go
  pkg/services/services.go
  test/e2e/create_test.go
  test/e2e/network_test.go
  test/e2e/storage_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2044 [release-4.12] OCPBUGS-28254: Use DSR load balancing in kube-proxy
  docs/byoh-instance-pre-requisites.md
  docs/vsphere-golden-image.md
  docs/vsphere_ci/scripts/install-firewall-rules.ps1
  pkg/secrets/secrets.go
  pkg/services/services.go
  test/e2e/create_test.go
  test/e2e/network_test.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2065 Grammar change in nutanix prequisites
  docs/nutanix-prerequisites.md
Labels: approved, lgtm

#2048 WINC-924: Move deprecated command line flags to KubeletConfiguration
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/nodeconfig_test.go
  pkg/services/services.go
Labels: approved, lgtm, jira/valid-reference

#2071 [release-4.13] build: Build Azure CCM with buildvcs=false
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
Labels: approved, lgtm

#1932 [release-4.12] OCPBUGS-23020: Introduce upgrading label to block concurrent upgrades
  controllers/controllers.go
  hack/common.sh
  hack/e2e/resources/parallel-upgrade-checker-job.yaml
  hack/run-ci-e2e-test.sh
  pkg/metadata/metadata.go
  pkg/nodeconfig/nodeconfig.go
  test/e2e/upgrade_test.go
  test/e2e/validation_test.go
  test/e2e/wmco_test.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2081 [release-4.12] submodule update 02 19
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#2083 [release-4.15] WINC-1113: Introduce feature annotations to CSV
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2084 [release-4.14] WINC-1113: Introduce feature annotations to CSV
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2082 WINC-1113: Introduce feature annotations to CSV
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2085 [release-4.13] WINC-1113: Introduce feature annotations to CSV
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2087 OCPBUGS-27775: [release-4.12] Introduce olm.skipRange to 7.2.1
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2093 WINC-1211: [release-4.15] Update version to 10.15.1
  .ci-operator.yaml
  Makefile
  bundle.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2086 [release-4.12] WINC-1113: Introduce feature annotations to CSV
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2096 [release-4.14] WINC-1113: Followup
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2089 [release-4.15] submodule update 02 26
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/modules.txt
Labels: approved, lgtm

#2092 [release-4.12] submodule update 02 26
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/modules.txt
Labels: approved, lgtm

#2098 WINC-1113: Followup
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2095 [release-4.13] WINC-1113: Followup
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference
