Repository openshift/windows-machine-config-operator, pull requests merged in 2024-12, with the labels that each got.

#2570 Adjust upgradeable condition timeout in test suite
  test/e2e/validation_test.go
Labels: approved, lgtm

#2541 WINC-1351: Fix WMCO's go build command to FIPS compliant
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  build/build.sh
Labels: approved, lgtm, jira/valid-reference

#2578 [release-4.17] Adjust konflux pipelines to work with Enterprise Contract
  .tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2580 [release-4.17] Enable hermetic builds for konflux
  .tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
Labels: approved, lgtm

#2579 WINC-1353: HPA support for Windows Containers
  README.md
Labels: approved, lgtm, jira/valid-reference

#2566 OCPBUGS-23121: Restart operator pod on malformed RBAC
  controllers/configmap_controller.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2581 [release-4-17] Use updated konflux images
  .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
Labels: approved, lgtm

#2589 [release-4.17] Adjust konflux builds
  .tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2590 Bump x/net to v0.33.0 and x/crypto to v0.31
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#2483 WINC-897: Regenerate servicesmanifest on rendered-worker update
  controllers/configmap_controller.go
Labels: approved, lgtm, jira/valid-reference
