Repository openshift/windows-machine-config-operator, pull requests merged in 2025-06, with the labels that each got.

#2969 [release-4.18] Update version to 10.18.2
  Containerfile
  Containerfile.bundle
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#2968 Change how extra arguments are processed
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  cmd/operator/main.go
  config/manager/manager.yaml
Labels: approved, lgtm

#2922 WINC-1376: Replace docs.openshift.com for docs.redhat.com
  Containerfile.bundle
  README.md
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  docs/HACKING.md
  docs/TROUBLESHOOTING.md
  docs/machineset-nutanix.md
  docs/nutanix-prerequisites.md
  docs/vsphere-golden-image.md
  docs/vsphere-prerequisites.md
  docs/wmco-prerequisites.md
  hack/community/csv/description.md
  pkg/services/services.go
  test/e2e/network_test.go
  test/e2e/providers/vsphere/vsphere.go
  test/e2e/storage_test.go
Labels: approved, lgtm, jira/valid-reference

#3000 [release-4.19] Fix tekton tasks
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4.19-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4.19-push.yaml
  .tekton/windows-machine-config-operator-release-4.19-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4.19-push.yaml
  Containerfile.bundle
Labels: approved, lgtm

#3005 [release-4.16] OCPBUGS-55939: Make debugLogging non-default
  build/Dockerfile.ci
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  cmd/operator/main.go
  config/manager/manager.yaml
  docs/TROUBLESHOOTING.md
  hack/run-ci-e2e-test.sh
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3004 [release-4.15] add script for cluster-wide proxy
  hack/setup-cluster-wide-proxy.sh
Labels: approved, lgtm

#3030 bump `sftp` to v1.13.9 and `x/crypto` to v0.39.0
  go.mod
  go.sum
  vendor/github.com/pkg/sftp/client.go
  vendor/github.com/pkg/sftp/internal/encoding/ssh/filexfer/openssh/fsync.go
  vendor/github.com/pkg/sftp/internal/encoding/ssh/filexfer/openssh/hardlink.go
  vendor/github.com/pkg/sftp/internal/encoding/ssh/filexfer/openssh/openssh.go
  vendor/github.com/pkg/sftp/internal/encoding/ssh/filexfer/openssh/posix-rename.go
  vendor/github.com/pkg/sftp/internal/encoding/ssh/filexfer/openssh/statvfs.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/connection.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/mac.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/mlkem.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/golang.org/x/mod/modfile/read.go
  vendor/golang.org/x/mod/modfile/rule.go
  vendor/golang.org/x/mod/modfile/work.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_riscv64.go
  vendor/golang.org/x/sys/cpu/cpu_riscv64.go
  vendor/golang.org/x/sys/windows/security_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, lgtm

#3028 [release-4.17] submodule update 06 10
  go.mod
  go.sum
  vendor/k8s.io/utils/buffer/ring_growing.go
  vendor/modules.txt
Labels: approved, lgtm

#3045 [release-4.16] Update version to 10.16.3
  Containerfile
  Containerfile.bundle
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm

#3050 Disable tekton pipelines for 4.12
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-push.yaml
  .tekton/windows-machine-config-operator-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-12-push.yaml
Labels: approved, lgtm
