Repository openshift/windows-machine-config-operator, pull requests merged in 2025-03, with the labels that each got.

#2730 OCPBUGS-50511: Wait for debug logging before running tests
  hack/run-ci-e2e-test.sh
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2704 WINC-1377: [release-4.15]Prep for konflux
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
  Containerfile
  Containerfile.bundle
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  build/build.sh
  build/bundle-konflux.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2742 OCPBUGS-48713: Improve debugging capabilities, code readability, and reliability in network tests
  test/e2e/network_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2605 OCPBUGS-45027: No Events Generated after changing cluster-monitoring Label
  controllers/metric_controller.go
Labels: approved, lgtm, ok-to-test, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2658 WINC-1365: Fix e2e warnings
  test/e2e/main_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
Labels: approved, lgtm, ok-to-test, jira/valid-reference

#2735 Stop depending on `jq` binary in e2e run script
  hack/common.sh
Labels: approved, lgtm

#2741 WINC-1378: Handle interrupt signals with the proper use of contexts
  cmd/daemon/bootstrap.go
  cmd/operator/main.go
  controllers/certificatesigningrequests_controller.go
  controllers/configmap_controller.go
  controllers/controllerconfig_controller.go
  controllers/controllers.go
  controllers/metric_controller.go
  controllers/node_controller.go
  controllers/registry_controller.go
  controllers/secret_controller.go
  controllers/windowsmachine_controller.go
  hack/lint-gofmt.sh
  pkg/cluster/config.go
  pkg/cluster/config_test.go
  pkg/condition/condition.go
  pkg/csr/csr.go
  pkg/daemon/cleanup/cleanup.go
  pkg/daemon/controller/controller.go
  pkg/daemon/controller/controller_test.go
  pkg/ignition/ignition.go
  pkg/nodeconfig/init.go
  pkg/nodeconfig/nodeconfig.go
  pkg/registries/registries.go
  pkg/secrets/secrets.go
  pkg/signer/signer.go
  pkg/windows/windows.go
  pkg/wiparser/wiparser.go
Labels: approved, lgtm, jira/valid-reference

#2753 OCPBUGS-52555: Bump x/oauth2 and x/crypto
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/text/internal/number/format.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2781 Allow Azure machineSet to conditionally set ManagedIdentity
  hack/machineset.sh
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm
