Repository openshift/windows-machine-config-operator, pull requests merged in 2025-08, with the labels that each got.

#3098 [release-4.15] WINC-1417: Update Konflux references and add image digest to task-sast-unicode-check-oci-ta
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
Labels: approved, lgtm, jira/valid-reference

#3113 [vendor] bump x/crypto to v0.40.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/trace/events.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/modules.txt
Labels: approved, lgtm

#3148 [vendor] bump x/crypto to v0.41.0
  go.mod
  go.sum
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_loong64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, lgtm

#3168 Reduce node retry interval in e2e tests
  test/e2e/wmco_test.go
Labels: approved, lgtm

#3197 OCPBUGS-60482: Fix SSH connection leak
  controllers/configmap_controller.go
  controllers/controllers.go
  controllers/node_controller.go
  controllers/registry_controller.go
  controllers/secret_controller.go
  pkg/csr/csr.go
  pkg/nodeconfig/init.go
  pkg/nodeconfig/nodeconfig.go
  pkg/windows/connectivity.go
  pkg/windows/windows.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#3187 WINC-1366: changes NodeSelector from master to control-plane
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, jira/valid-reference

#3223 Fix sshConnectivity close error handling
  pkg/windows/connectivity.go
Labels: approved, lgtm

#3232 [release-4.14] WINC-1440: Remove deprecated version build infrastructure
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-push.yaml
  .tekton/windows-machine-config-operator-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-14-push.yaml
Labels: approved, lgtm, jira/valid-reference

#3233 [release-4.15] WINC-1440: Removes deprecated version build infrastructure
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
Labels: approved, lgtm, jira/valid-reference

#3202 OCPBUGS-60771: Fix job success logic
  test/e2e/network_test.go
  test/e2e/upgrade_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#3224 WINC-1442: Save configuration time data to artifacts directory
  test/e2e/create_test.go
  test/e2e/logs_test.go
  test/e2e/main_test.go
  test/e2e/network_test.go
Labels: approved, lgtm, jira/valid-reference
