Repository openshift/windows-machine-config-operator, pull requests merged in 2025-02, with the labels that each got.

#2663 Use golang builder image and bundle dockerfile in line with OCP 4.19
  .ci-operator.yaml
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  bundle.Dockerfile
Labels: approved, lgtm

#2640 Add node object to e2e artifacts and remove unused test code
  .gitignore
  test/e2e/create_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#2670 [release-4.17] submodule update 02 03
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/spf13/pflag/.editorconfig
  vendor/github.com/spf13/pflag/.golangci.yaml
  vendor/modules.txt
Labels: approved, lgtm

#2662 [release-4.18] WINC-1351: Fix WMCO's go build command to FIPS compliant and set strictfipsruntime
  .tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml
  Containerfile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  build/build.sh
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2699 OCPBUGS-50511: Make debugLogging non-default
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  docs/TROUBLESHOOTING.md
  hack/run-ci-e2e-test.sh
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2673 WINC-720: Improve network tests and add packet trace
  go.mod
  test/e2e/create_test.go
  test/e2e/network_test.go
Labels: approved, lgtm, jira/valid-reference

#2689 WINC-1362: Update fips task ref
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2711 Disable submodule renovate
  renovate.json
Labels: approved, lgtm

#2702 [release-4.17] Prep for konflux release
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
  Containerfile
  Containerfile.bundle
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#2718 [release-4.18] Update konflux build definitions
  .tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml
  Containerfile
Labels: approved, lgtm

#2703 WINC-1377 : [release-4.16] Prep for konflux release
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml
  .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-16-push.yaml
  Containerfile
  Containerfile.bundle
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  build/build.sh
  build/bundle-konflux.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#2736 Replace date in CSV at build time
  Containerfile.bundle
Labels: approved, lgtm

#2737 [release-4.18] Replace date in CSV at build time
  Containerfile.bundle
Labels: approved, lgtm

#2738 [release-4.17] Replace date in CSV at build time
  Containerfile.bundle
Labels: approved, lgtm

#2739 [release-4.16] Replace date in CSV at build time
  Containerfile.bundle
Labels: approved, lgtm
