Repository openshift/windows-machine-config-operator, pull requests merged in 2025-04, with the labels that each got.

#2788 Add shell and unicode sast pipeline tasks
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
Labels: approved, lgtm

#2789 [release 4.18] Add shell and unicode sast pipeline tasks
  .tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml
  .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-18-push.yaml
Labels: approved, lgtm

#2797 WINC-1380 [release-4.18] - increases resource limits to avoid OOMkilling
  .tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml
  .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-18-push.yaml
Labels: approved, lgtm

#2796 [WINC-1380] increases resource limits to avoid OOMkilling
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
Labels: approved, lgtm

#2784 OCPBUGS-54313: [release-4.17] Make debugLogging non-default
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  docs/TROUBLESHOOTING.md
  hack/run-ci-e2e-test.sh
  test/e2e/validation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2790 WINC-1380: [release-4.17] Add shell and unicode sast pipeline tasks
  .tekton/windows-machine-config-operator-bundle-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-17-push.yaml
  .tekton/windows-machine-config-operator-release-4-17-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-17-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2791 WINC-1380: [release-4.16] Add shell and unicode sast pipeline tasks
  .tekton/windows-machine-config-operator-bundle-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-16-push.yaml
  .tekton/windows-machine-config-operator-release-4-16-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-16-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2792 WINC-1380: [release-4.15] Add shell and unicode sast pipeline tasks
  .tekton/windows-machine-config-operator-bundle-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-15-push.yaml
  .tekton/windows-machine-config-operator-release-4-15-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-15-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2794 OCPBUGS-54499: bump ignition to 3.5
  pkg/ignition/ignition.go
  pkg/nodeconfig/nodeconfig.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/config.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/translate/translate.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/cex.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/clevis.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/config.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/device.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/directory.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/disk.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/file.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/filesystem.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/headers.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/ignition.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/kargs.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/luks.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/mode.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/node.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/partition.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/passwd.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/path.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/proxy.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/raid.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/resource.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/schema.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/storage.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/systemd.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/tang.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/tls.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/unit.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/url.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/verification.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2795 [release-4.18] bump ignition to 3.5
  pkg/ignition/ignition.go
  pkg/nodeconfig/nodeconfig.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/config.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/translate/translate.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/cex.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/clevis.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/config.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/device.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/directory.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/disk.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/file.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/filesystem.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/headers.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/ignition.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/kargs.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/luks.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/mode.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/node.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/partition.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/passwd.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/path.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/proxy.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/raid.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/resource.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/schema.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/storage.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/systemd.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/tang.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/tls.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/unit.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/url.go
  vendor/github.com/coreos/ignition/v2/config/v3_5/types/verification.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#2760 OCPBUGS-53143: bumps aws-sdk-go and sftp
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/session/shared_config.go
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/github.com/pkg/sftp/client.go
  vendor/github.com/pkg/sftp/server.go
  vendor/github.com/pkg/sftp/server_posix.go
  vendor/github.com/pkg/sftp/server_windows.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2809 OCPBUGS-35285: bump AWS EC2LaunchV2 min version to 2.0.2107
  pkg/secrets/secrets.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2786 Update hack/machineset.sh
  hack/machineset.sh
Labels: approved, lgtm

#2811 WINC-1383: Increase memory for konflux tasks that OOM
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2817 WINC-1383: Increase build-container task memory
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2799 OCPBUGS-47696: Fix containerd host.toml generation to work with mirrors using an org_name
  README.md
  pkg/registries/registries.go
  pkg/registries/registries_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#2833 WINC-1383: Bump use-trusted-artifact step memory
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
Labels: approved, lgtm, jira/valid-reference

#2798 [release-4.14] Prep for konflux
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-14-push.yaml
  .tekton/windows-machine-config-operator-release-4-14-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-14-push.yaml
  Containerfile
  Containerfile.bundle
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  build/build.sh
  build/bundle-konflux.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test

#2831 [release-4.16] WINC-1365: Fix e2e warnings
  test/e2e/main_test.go
  test/e2e/network_test.go
  test/e2e/providers/aws/aws.go
Labels: approved, lgtm, jira/valid-reference

#2842 WINC-1359: Prep for 10.18.1 release
  Containerfile
  Containerfile.bundle
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2709 WINC-1374,WINC-926,WINC-1373: Adjust kubelet configuration for NodeAllocatable, EvictionHard and System Memory
  pkg/nodeconfig/nodeconfig.go
  pkg/nodeconfig/nodeconfig_test.go
Labels: approved, lgtm, jira/valid-reference

#2783 WINC-1189: Add publicLoadBalancer to azure test VMs
  test/e2e/providers/azure/azure.go
Labels: approved, lgtm, jira/valid-reference

#2848 [release-4.12] WINC-1377: Prep for konflux
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-12-push.yaml
  .tekton/windows-machine-config-operator-release-4-12-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-12-push.yaml
  Containerfile
  Containerfile.bundle
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  build/build.sh
  build/bundle-konflux.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
  vendor/github.com/go-errors/errors/cover.out
Labels: approved, lgtm, jira/valid-reference
