Repository openshift/windows-machine-config-operator, pull requests merged in 2025-01, with the labels that each got.

#2564 Fix incorrect rolebinding error message and improve logging
  cmd/operator/main.go
  controllers/configmap_controller.go
Labels: approved, lgtm

#2591 [release-4.18] OCPBUGS-47444: Bump x/net to v0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2597 Update konflux build pipeline
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2600 [release-4.18] Update konflux build pipeline
  .tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml
  .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-18-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2604 [release-4.18] Konflux changes to make WMCO bundle usable
  .tekton/images-mirror-set.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2592 [release-4.17] OCPBUGS-47443: Bump x/net to v0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2606 Konflux build adjustments
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2609 [build] Fix bundle image reference
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2610 [build] Use latest operator image
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2611 Add version label to operator image
  build/Dockerfile.konflux
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm

#2612 Change operator image ref to stage
  .tekton/images-mirror-set.yaml
  build/bundle-konflux.Dockerfile
Labels: approved, lgtm, ok-to-test

#2615 WINC-1354: 4.19 branching tasks
  .tekton/windows-machine-config-operator-bundle-master-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-master-push.yaml
  .tekton/windows-machine-config-operator-master-pull-request.yaml
  .tekton/windows-machine-config-operator-master-push.yaml
  Containerfile
  Containerfile.bundle
  Makefile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/windows-machine-config-operator.package.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2603 Bump x/net to v0.34.0 and x/crypto to v0.32
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#2621 [build] Fix missed filename change
  .tekton/windows-machine-config-operator-master-pull-request.yaml
Labels: approved, lgtm

#2620 [release-4.18] Rename konflux containerfiles
  .tekton/windows-machine-config-operator-bundle-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-18-push.yaml
  .tekton/windows-machine-config-operator-release-4-18-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-18-push.yaml
  Containerfile
  Containerfile.bundle
  bundle/metadata/annotations.yaml
Labels: approved, lgtm

#2639 [release-4.18] Fix WMCO image reference
  Containerfile.bundle
Labels: approved, lgtm

#2636 OCPBUGS-36671: Use WICD kubeconfig for Azure CCM
  bundle/manifests/windows-instance-config-daemon_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/wicd/windows-instance-config-daemon-cluster-role.yaml
  controllers/configmap_controller.go
  go.mod
  go.sum
  pkg/nodeconfig/nodeconfig.go
  pkg/services/services.go
  pkg/windows/windows.go
  test/e2e/create_test.go
  test/e2e/validation_test.go
  vendor/k8s.io/cloud-provider/node/helpers/address.go
  vendor/k8s.io/cloud-provider/node/helpers/labels.go
  vendor/k8s.io/cloud-provider/node/helpers/taints.go
  vendor/k8s.io/component-helpers/LICENSE
  vendor/k8s.io/component-helpers/node/util/cidr.go
  vendor/k8s.io/component-helpers/node/util/conditions.go
  vendor/k8s.io/component-helpers/node/util/hostname.go
  vendor/k8s.io/component-helpers/node/util/ips.go
  vendor/k8s.io/component-helpers/node/util/status.go
  vendor/modules.txt
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2633 [release-4.15] OCPBUGS-47440: Bump x/net to v0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64x.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64x.s
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.s
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/sys/cpu/asm_darwin_x86_gc.s
  vendor/golang.org/x/sys/cpu/cpu_darwin_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.go
  vendor/golang.org/x/sys/cpu/cpu_gc_x86.s
  vendor/golang.org/x/sys/cpu/cpu_gccgo_x86.go
  vendor/golang.org/x/sys/cpu/cpu_linux_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_other_x86.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/cpu/syscall_darwin_x86_gc.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_zos_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_darwin_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_zos_s390x.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/term/README.md
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2651 Run with GOEXPERIMENT var strictfipsruntime
  Containerfile
Labels: approved, lgtm
