Repository openshift/windows-machine-config-operator, pull requests merged in 2025-05, with the labels that each got.

#2828 OCPBUGS-52423: adds retries to oc cp
  test/e2e/network_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2855 [release-4.17] WINC-1351: Enable FIPS compliance
  Containerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  config/manifests/bases/windows-machine-config-operator.clusterserviceversion.yaml
Labels: approved, lgtm, jira/valid-reference

#2840 [release-4.15] Update operator image digest
  Containerfile.bundle
Labels: approved, lgtm

#2850 OCPBUGS-55614: Avoid copying containerd registry files to deleted nodes
  controllers/registry_controller.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#2849 Fix unknown verb in message and ignore SSH known hosts in test suite
  test/e2e/certificates_test.go
  test/e2e/validation_test.go
Labels: approved, lgtm

#2881 branching day tasks for 4.20 release
  .gitmodules
  Containerfile
  Containerfile.bundle
  Makefile
  build/Dockerfile
  build/Dockerfile.base
  build/Dockerfile.ci
  build/Dockerfile.wmco
  bundle.Dockerfile
  bundle/manifests/windows-machine-config-operator.clusterserviceversion.yaml
  bundle/windows-machine-config-operator.package.yaml
Labels: approved, lgtm

#2859 vendor: fix golang-jwt to v4.5.2 and v5.2.2
  go.mod
  vendor/modules.txt
Labels: approved, lgtm

#2857 vendor updates 05 02
  go.mod
  go.sum
  vendor/github.com/aws/aws-sdk-go/aws/version.go
  vendor/golang.org/x/crypto/internal/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_asm.go
  vendor/golang.org/x/crypto/internal/poly1305/sum_loong64.s
  vendor/golang.org/x/crypto/internal/poly1305/sum_ppc64x.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/oauth2/token.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_linux_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_linux_noinit.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.go
  vendor/golang.org/x/sys/cpu/cpu_loong64.s
  vendor/golang.org/x/sys/cpu/parse.go
  vendor/golang.org/x/sys/unix/syscall_darwin.go
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_darwin_arm64.s
  vendor/golang.org/x/sys/windows/registry/key.go
  vendor/golang.org/x/sys/windows/registry/value.go
  vendor/golang.org/x/sys/windows/svc/mgr/config.go
  vendor/golang.org/x/sys/windows/svc/mgr/mgr.go
  vendor/golang.org/x/sys/windows/svc/mgr/recovery.go
  vendor/golang.org/x/sys/windows/svc/mgr/service.go
  vendor/golang.org/x/sys/windows/svc/service.go
  vendor/golang.org/x/sys/windows/types_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, lgtm

#2880 [release-4.19] branching day tasks for 4.20 release
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4.19-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4.19-push.yaml
  .tekton/windows-machine-config-operator-release-4.19-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4.19-push.yaml
Labels: approved, lgtm

#2858 [release-4.18] OCPBUGS-51967,OCPBUGS-51980,OCPBUGS-54113: update vendor deps oauth2, crypto and jwt
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2779 OCPBUGS-54224: removed the FAILED keyword to not depend on internationalization
  pkg/windows/windows.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#2944 React to master application removal
  .tekton/images-mirror-set.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-20-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-20-push.yaml
  .tekton/windows-machine-config-operator-release-4-20-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-20-push.yaml
Labels: approved, lgtm

#2951 [build] Use registry.redhat.io operator image
  Containerfile.bundle
Labels: approved, lgtm

#2939 [release-4.17] OCPBUGS-51979: use openshift/golang-crypto v0.33.1
  go.mod
  vendor/modules.txt
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#2963 [release-4.13] Remove konflux build files
  .tekton/windows-machine-config-operator-bundle-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-bundle-release-4-13-push.yaml
  .tekton/windows-machine-config-operator-release-4-13-pull-request.yaml
  .tekton/windows-machine-config-operator-release-4-13-push.yaml
Labels: approved, lgtm
